name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code sample
      description: If applicable, provide a minimal code sample that demonstrates the issue
      render: go
      placeholder: |
        package main
        
        import "github.com/lazygophers/utils/candy"
        
        func main() {
            // Your code here
        }

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of LazyGophers Utils are you running?
      placeholder: e.g., v1.0.0, latest
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go version
      description: What version of Go are you using?
      placeholder: e.g., go1.24.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - FreeBSD
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment details
      description: Please provide any additional environment details
      placeholder: |
        - Architecture: amd64/arm64
        - Distribution: Ubuntu 22.04
        - Container: Docker/Podman
        - Other relevant details

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/lazygophers/utils/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true