package fake

func init() {
	registerDataSet("zh-TW", "addresses", "cities", dsZhtw_0)
	registerDataSet("zh-TW", "addresses", "streets", dsZhtw_1)
	registerDataSet("zh-TW", "companies", "names", dsZhtw_2)
	registerDataSet("zh-TW", "companies", "suffixes", dsZhtw_3)
	registerDataSet("zh-TW", "names", "first_female", dsZhtw_4)
	registerDataSet("zh-TW", "names", "first_male", dsZhtw_5)
	registerDataSet("zh-TW", "names", "last", dsZhtw_6)
	registerDataSet("zh-TW", "texts", "lorem", dsZhtw_7)
}

var dsZhtw_0 = &DataSet{
	Language: "zh-TW",
	Country:  "TW",
	Type:     "addresses",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "臺北市", Weight: 3.0, Tags: []string{"major", "capital", "north"}, Meta: map[string]string{"county": "臺北", "zip_prefix": "10", "population": "2602418", "tier": "1", "region": "north"}},
		{Value: "新北市", Weight: 2.8, Tags: []string{"major", "metropolitan", "north"}, Meta: map[string]string{"county": "新北", "zip_prefix": "20", "population": "4030954", "tier": "1", "region": "north"}},
		{Value: "高雄市", Weight: 2.6, Tags: []string{"major", "port", "south"}, Meta: map[string]string{"county": "高雄", "zip_prefix": "80", "population": "2773533", "tier": "1", "region": "south"}},
		{Value: "臺中市", Weight: 2.4, Tags: []string{"major", "central", "manufacturing"}, Meta: map[string]string{"county": "臺中", "zip_prefix": "40", "population": "2820787", "tier": "1", "region": "central"}},
		{Value: "臺南市", Weight: 2.0, Tags: []string{"major", "historical", "south"}, Meta: map[string]string{"county": "臺南", "zip_prefix": "70", "population": "1873794", "tier": "2", "region": "south"}},
		{Value: "桃園市", Weight: 1.8, Tags: []string{"major", "airport", "north"}, Meta: map[string]string{"county": "桃園", "zip_prefix": "32", "population": "2268807", "tier": "2", "region": "north"}},
		{Value: "新竹市", Weight: 1.6, Tags: []string{"technology", "tech", "north"}, Meta: map[string]string{"county": "新竹", "zip_prefix": "30", "population": "453046", "tier": "2", "region": "north"}},
		{Value: "基隆市", Weight: 1.4, Tags: []string{"port", "coastal", "north"}, Meta: map[string]string{"county": "基隆", "zip_prefix": "20", "population": "367577", "tier": "3", "region": "north"}},
		{Value: "新竹縣", Weight: 1.2, Tags: []string{"technology", "rural", "north"}, Meta: map[string]string{"county": "新竹", "zip_prefix": "30", "population": "572656", "tier": "3", "region": "north"}},
		{Value: "苗栗縣", Tags: []string{"rural", "agriculture", "central"}, Meta: map[string]string{"county": "苗栗", "zip_prefix": "35", "population": "543076", "tier": "3", "region": "central"}},
		{Value: "彰化縣", Tags: []string{"agriculture", "traditional", "central"}, Meta: map[string]string{"county": "彰化", "zip_prefix": "50", "population": "1270140", "tier": "3", "region": "central"}},
		{Value: "南投縣", Weight: 0.9, Tags: []string{"mountainous", "tourism", "central"}, Meta: map[string]string{"county": "南投", "zip_prefix": "54", "population": "495981", "tier": "4", "region": "central"}},
		{Value: "雲林縣", Weight: 0.9, Tags: []string{"agriculture", "rural", "south"}, Meta: map[string]string{"county": "雲林", "zip_prefix": "63", "population": "687540", "tier": "4", "region": "south"}},
		{Value: "嘉義市", Weight: 0.8, Tags: []string{"small", "central", "south"}, Meta: map[string]string{"county": "嘉義", "zip_prefix": "60", "population": "266757", "tier": "4", "region": "south"}},
		{Value: "嘉義縣", Weight: 0.8, Tags: []string{"agriculture", "rural", "south"}, Meta: map[string]string{"county": "嘉義", "zip_prefix": "61", "population": "508842", "tier": "4", "region": "south"}},
		{Value: "屏東縣", Weight: 0.7, Tags: []string{"rural", "tropical", "south"}, Meta: map[string]string{"county": "屏東", "zip_prefix": "90", "population": "818748", "tier": "4", "region": "south"}},
		{Value: "宜蘭縣", Weight: 0.6, Tags: []string{"coastal", "tourism", "east"}, Meta: map[string]string{"county": "宜蘭", "zip_prefix": "26", "population": "458734", "tier": "4", "region": "east"}},
		{Value: "花蓮縣", Weight: 0.6, Tags: []string{"mountainous", "indigenous", "east"}, Meta: map[string]string{"county": "花蓮", "zip_prefix": "97", "population": "327754", "tier": "4", "region": "east"}},
		{Value: "臺東縣", Weight: 0.5, Tags: []string{"rural", "indigenous", "east"}, Meta: map[string]string{"county": "臺東", "zip_prefix": "95", "population": "217547", "tier": "4", "region": "east"}},
		{Value: "澎湖縣", Weight: 0.4, Tags: []string{"island", "tourism", "west"}, Meta: map[string]string{"county": "澎湖", "zip_prefix": "88", "population": "106327", "tier": "5", "region": "west"}},
		{Value: "金門縣", Weight: 0.3, Tags: []string{"island", "military", "west"}, Meta: map[string]string{"county": "金門", "zip_prefix": "89", "population": "140716", "tier": "5", "region": "west"}},
		{Value: "連江縣", Weight: 0.2, Tags: []string{"island", "remote", "west"}, Meta: map[string]string{"county": "連江", "zip_prefix": "21", "population": "13076", "tier": "5", "region": "west"}},
	},
}

var dsZhtw_1 = &DataSet{
	Language: "zh-TW",
	Country:  "TW",
	Type:     "addresses",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "中山路", Weight: 2.5, Tags: []string{"historical", "memorial"}},
		{Value: "中正路", Weight: 2.0, Tags: []string{"political", "memorial"}},
		{Value: "民族路", Weight: 1.8, Tags: []string{"patriotic", "nationalism"}},
		{Value: "民權路", Weight: 1.6, Tags: []string{"political", "rights"}},
		{Value: "民生路", Weight: 1.4, Tags: []string{"livelihood", "welfare"}},
		{Value: "復興路", Weight: 1.2, Tags: []string{"revival", "renaissance"}},
		{Value: "光復路", Tags: []string{"liberation", "restoration"}},
		{Value: "信義路", Tags: []string{"trust", "righteousness"}},
		{Value: "仁愛路", Weight: 0.9, Tags: []string{"benevolence", "love"}},
		{Value: "和平路", Weight: 0.9, Tags: []string{"peace"}},
		{Value: "忠孝路", Weight: 0.8, Tags: []string{"loyalty", "filial"}},
		{Value: "建國路", Weight: 0.8, Tags: []string{"nation-building"}},
		{Value: "中華路", Weight: 0.7, Tags: []string{"chinese", "cultural"}},
		{Value: "自由路", Weight: 0.7, Tags: []string{"freedom", "liberty"}},
		{Value: "文化路", Weight: 0.6, Tags: []string{"culture", "education"}},
		{Value: "教育路", Weight: 0.6, Tags: []string{"education", "academic"}},
		{Value: "學府路", Weight: 0.5, Tags: []string{"academic", "scholarly"}},
		{Value: "青年路", Weight: 0.5, Tags: []string{"youth", "young"}},
		{Value: "博愛路", Weight: 0.5, Tags: []string{"universal-love", "fraternity"}},
		{Value: "三民路", Weight: 0.4, Tags: []string{"political", "republican"}},
		{Value: "大同路", Weight: 0.4, Tags: []string{"unity", "harmony"}},
		{Value: "勝利路", Weight: 0.4, Tags: []string{"victory", "triumph"}},
		{Value: "成功路", Weight: 0.4, Tags: []string{"success", "achievement"}},
		{Value: "幸福路", Weight: 0.4, Tags: []string{"happiness", "welfare"}},
		{Value: "健康路", Weight: 0.4, Tags: []string{"health", "wellness"}},
		{Value: "永康街", Weight: 0.3, Tags: []string{"eternal", "health"}},
		{Value: "師大路", Weight: 0.3, Tags: []string{"university", "education"}},
		{Value: "羅斯福路", Weight: 0.3, Tags: []string{"international", "memorial"}},
		{Value: "敦化南路", Weight: 0.3, Tags: []string{"cultivation", "refinement"}},
		{Value: "基隆路", Weight: 0.3, Tags: []string{"geographical"}},
		{Value: "承德路", Weight: 0.2, Tags: []string{"historical", "imperial"}},
		{Value: "重慶南路", Weight: 0.2, Tags: []string{"geographical", "bookstore"}},
		{Value: "西門町", Weight: 0.2, Tags: []string{"commercial", "entertainment"}},
	},
}

var dsZhtw_2 = &DataSet{
	Language: "zh-TW",
	Country:  "TW",
	Type:     "companies",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "台積電", Weight: 3.0, Tags: []string{"tech", "semiconductor"}, Meta: map[string]string{"industry": "technology", "founded": "1987", "type": "public"}},
		{Value: "鴻海", Weight: 2.8, Tags: []string{"tech", "manufacturing"}, Meta: map[string]string{"industry": "technology", "founded": "1974", "type": "public"}},
		{Value: "聯發科", Weight: 2.6, Tags: []string{"tech", "semiconductor"}, Meta: map[string]string{"industry": "technology", "founded": "1997", "type": "public"}},
		{Value: "華碩", Weight: 2.4, Tags: []string{"tech", "computer"}, Meta: map[string]string{"industry": "technology", "founded": "1989", "type": "public"}},
		{Value: "宏碁", Weight: 2.2, Tags: []string{"tech", "computer"}, Meta: map[string]string{"industry": "technology", "founded": "1976", "type": "public"}},
		{Value: "廣達", Weight: 2.0, Tags: []string{"tech", "manufacturing"}, Meta: map[string]string{"industry": "technology", "founded": "1988", "type": "public"}},
		{Value: "英業達", Weight: 1.8, Tags: []string{"tech", "manufacturing"}, Meta: map[string]string{"industry": "technology", "founded": "1975", "type": "public"}},
		{Value: "和碩", Weight: 1.6, Tags: []string{"tech", "manufacturing"}, Meta: map[string]string{"industry": "technology", "founded": "2007", "type": "public"}},
		{Value: "仁寶", Weight: 1.4, Tags: []string{"tech", "manufacturing"}, Meta: map[string]string{"industry": "technology", "founded": "1984", "type": "public"}},
		{Value: "緯創", Weight: 1.2, Tags: []string{"tech", "manufacturing"}, Meta: map[string]string{"industry": "technology", "founded": "2001", "type": "public"}},
		{Value: "聯電", Tags: []string{"tech", "semiconductor"}, Meta: map[string]string{"industry": "technology", "founded": "1980", "type": "public"}},
		{Value: "日月光", Tags: []string{"tech", "semiconductor"}, Meta: map[string]string{"industry": "technology", "founded": "1984", "type": "public"}},
		{Value: "台達電", Weight: 0.9, Tags: []string{"tech", "electronics"}, Meta: map[string]string{"industry": "technology", "founded": "1971", "type": "public"}},
		{Value: "中華電信", Weight: 0.9, Tags: []string{"telecom", "state"}, Meta: map[string]string{"industry": "telecommunications", "founded": "1996", "type": "public"}},
		{Value: "遠傳電信", Weight: 0.8, Tags: []string{"telecom"}, Meta: map[string]string{"industry": "telecommunications", "founded": "1997", "type": "public"}},
		{Value: "台灣大哥大", Weight: 0.8, Tags: []string{"telecom"}, Meta: map[string]string{"industry": "telecommunications", "founded": "1997", "type": "public"}},
		{Value: "中油", Weight: 0.7, Tags: []string{"energy", "oil", "state"}, Meta: map[string]string{"industry": "energy", "founded": "1946", "type": "state"}},
		{Value: "台電", Weight: 0.7, Tags: []string{"energy", "electricity", "state"}, Meta: map[string]string{"industry": "energy", "founded": "1946", "type": "state"}},
		{Value: "中鋼", Weight: 0.6, Tags: []string{"steel", "manufacturing", "state"}, Meta: map[string]string{"industry": "manufacturing", "founded": "1971", "type": "public"}},
		{Value: "長榮", Weight: 0.6, Tags: []string{"shipping", "airline"}, Meta: map[string]string{"industry": "transportation", "founded": "1968", "type": "public"}},
		{Value: "陽明海運", Weight: 0.5, Tags: []string{"shipping"}, Meta: map[string]string{"industry": "transportation", "founded": "1972", "type": "public"}},
		{Value: "華航", Weight: 0.5, Tags: []string{"airline", "transportation"}, Meta: map[string]string{"industry": "transportation", "founded": "1959", "type": "public"}},
		{Value: "富邦金", Weight: 0.5, Tags: []string{"finance", "banking"}, Meta: map[string]string{"industry": "finance", "founded": "1961", "type": "public"}},
		{Value: "國泰金", Weight: 0.5, Tags: []string{"finance", "insurance"}, Meta: map[string]string{"industry": "finance", "founded": "1962", "type": "public"}},
		{Value: "中信金", Weight: 0.4, Tags: []string{"finance", "banking"}, Meta: map[string]string{"industry": "finance", "founded": "1966", "type": "public"}},
		{Value: "玉山金", Weight: 0.4, Tags: []string{"finance", "banking"}, Meta: map[string]string{"industry": "finance", "founded": "1992", "type": "public"}},
		{Value: "台新金", Weight: 0.4, Tags: []string{"finance", "banking"}, Meta: map[string]string{"industry": "finance", "founded": "1992", "type": "public"}},
		{Value: "遠東集團", Weight: 0.4, Tags: []string{"conglomerate"}, Meta: map[string]string{"industry": "conglomerate", "founded": "1937", "type": "private"}},
		{Value: "統一企業", Weight: 0.4, Tags: []string{"food", "retail"}, Meta: map[string]string{"industry": "food", "founded": "1967", "type": "public"}},
		{Value: "味全", Weight: 0.3, Tags: []string{"food", "dairy"}, Meta: map[string]string{"industry": "food", "founded": "1953", "type": "public"}},
		{Value: "康師傅", Weight: 0.3, Tags: []string{"food", "beverage"}, Meta: map[string]string{"industry": "food", "founded": "1992", "type": "public"}},
		{Value: "旺旺", Weight: 0.3, Tags: []string{"food", "snack"}, Meta: map[string]string{"industry": "food", "founded": "1983", "type": "public"}},
		{Value: "台塑", Weight: 0.3, Tags: []string{"petrochemical", "manufacturing"}, Meta: map[string]string{"industry": "petrochemical", "founded": "1954", "type": "public"}},
		{Value: "南亞", Weight: 0.3, Tags: []string{"petrochemical", "manufacturing"}, Meta: map[string]string{"industry": "petrochemical", "founded": "1958", "type": "public"}},
		{Value: "台化", Weight: 0.3, Tags: []string{"petrochemical", "manufacturing"}, Meta: map[string]string{"industry": "petrochemical", "founded": "1965", "type": "public"}},
	},
}

var dsZhtw_3 = &DataSet{
	Language: "zh",
	Country:  "TW",
	Type:     "companies",
	Version:  "1.0.0",
	Items: []DataItem{
		{Value: "有限公司", Weight: 3.0, Tags: []string{"common", "limited"}},
		{Value: "股份有限公司", Weight: 2.5, Tags: []string{"common", "corporation"}},
		{Value: "集團", Weight: 2.0, Tags: []string{"large", "group"}},
		{Value: "控股", Weight: 1.8, Tags: []string{"holding", "investment"}},
		{Value: "科技", Weight: 1.6, Tags: []string{"technology", "modern"}},
		{Value: "實業", Weight: 1.4, Tags: []string{"industrial", "manufacturing"}},
		{Value: "貿易", Weight: 1.2, Tags: []string{"trading", "commerce"}},
		{Value: "投資", Tags: []string{"investment", "financial"}},
		{Value: "發展", Weight: 0.9, Tags: []string{"development", "growth"}},
		{Value: "建設", Weight: 0.8, Tags: []string{"construction", "infrastructure"}},
	},
}

var dsZhtw_4 = &DataSet{
	Language: "zh-TW",
	Country:  "TW",
	Type:     "names",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "美", Weight: 2.0, Tags: []string{"beautiful"}},
		{Value: "雅", Weight: 1.9, Tags: []string{"elegant", "refined"}},
		{Value: "婷", Weight: 1.8, Tags: []string{"graceful", "elegant"}},
		{Value: "怡", Weight: 1.7, Tags: []string{"pleasant", "happy"}},
		{Value: "玲", Weight: 1.6, Tags: []string{"elegant", "delicate"}},
		{Value: "慧", Weight: 1.5, Tags: []string{"wise", "intelligent"}},
		{Value: "君", Weight: 1.4, Tags: []string{"noble", "ruler"}},
		{Value: "秀", Weight: 1.3, Tags: []string{"elegant", "beautiful"}},
		{Value: "芳", Weight: 1.2, Tags: []string{"fragrant", "virtue"}},
		{Value: "珮", Weight: 1.1, Tags: []string{"precious", "jade"}},
		{Value: "琳", Tags: []string{"precious", "jade"}},
		{Value: "儀", Tags: []string{"ceremony", "graceful"}},
		{Value: "瑩", Tags: []string{"crystal", "bright"}},
		{Value: "靜", Weight: 0.9, Tags: []string{"peaceful", "quiet"}},
		{Value: "敏", Weight: 0.9, Tags: []string{"smart", "agile"}},
		{Value: "倩", Weight: 0.9, Tags: []string{"beautiful", "charming"}},
		{Value: "淑", Weight: 0.8, Tags: []string{"gentle", "virtuous"}},
		{Value: "菁", Weight: 0.8, Tags: []string{"essence", "elite"}},
		{Value: "麗", Weight: 0.8, Tags: []string{"beautiful"}},
		{Value: "霞", Weight: 0.7, Tags: []string{"nature", "sunset"}},
		{Value: "萍", Weight: 0.7, Tags: []string{"nature", "water"}},
		{Value: "華", Weight: 0.7, Tags: []string{"magnificent", "china"}},
		{Value: "惠", Weight: 0.6, Tags: []string{"kind", "benevolent"}},
		{Value: "珊", Weight: 0.6, Tags: []string{"coral", "precious"}},
		{Value: "欣", Weight: 0.6, Tags: []string{"happy", "joyful"}},
		{Value: "瑜", Weight: 0.5, Tags: []string{"precious", "jade"}},
		{Value: "晴", Weight: 0.5, Tags: []string{"sunny", "clear"}},
		{Value: "蓉", Weight: 0.5, Tags: []string{"flower", "lotus"}},
		{Value: "姿", Weight: 0.5, Tags: []string{"posture", "graceful"}},
		{Value: "涵", Weight: 0.4, Tags: []string{"cultivated", "inclusive"}},
		{Value: "詩", Weight: 0.4, Tags: []string{"literary", "poetic"}},
		{Value: "語", Weight: 0.4, Tags: []string{"communication", "speech"}},
		{Value: "茹", Weight: 0.4, Tags: []string{"gentle", "soft"}},
		{Value: "娟", Weight: 0.4, Tags: []string{"beautiful", "graceful"}},
		{Value: "薇", Weight: 0.3, Tags: []string{"flower", "rose"}},
		{Value: "瑤", Weight: 0.3, Tags: []string{"precious", "mythical", "jade"}},
		{Value: "馨", Weight: 0.3, Tags: []string{"fragrant", "sweet"}},
		{Value: "妍", Weight: 0.3, Tags: []string{"beautiful", "lovely"}},
		{Value: "嫻", Weight: 0.3, Tags: []string{"elegant", "refined"}},
		{Value: "璇", Weight: 0.3, Tags: []string{"beautiful", "jade"}},
		{Value: "心", Weight: 0.3, Tags: []string{"pure", "simple", "heart"}},
	},
}

var dsZhtw_5 = &DataSet{
	Language: "zh-TW",
	Country:  "TW",
	Type:     "names",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "志", Weight: 2.0, Tags: []string{"will", "ambition"}},
		{Value: "偉", Weight: 1.8, Tags: []string{"great", "mighty"}},
		{Value: "明", Weight: 1.6, Tags: []string{"bright", "intelligent"}},
		{Value: "宏", Weight: 1.4, Tags: []string{"grand", "vast"}},
		{Value: "文", Weight: 1.3, Tags: []string{"culture", "literary"}},
		{Value: "建", Weight: 1.2, Tags: []string{"build", "establish"}},
		{Value: "傑", Weight: 1.1, Tags: []string{"outstanding", "hero"}},
		{Value: "勇", Tags: []string{"brave", "courageous"}},
		{Value: "強", Tags: []string{"strong", "powerful"}},
		{Value: "軍", Tags: []string{"military", "soldier"}},
		{Value: "華", Weight: 0.9, Tags: []string{"magnificent", "china"}},
		{Value: "宇", Weight: 0.9, Tags: []string{"universe", "space"}},
		{Value: "博", Weight: 0.9, Tags: []string{"learned", "extensive"}},
		{Value: "昊", Weight: 0.8, Tags: []string{"sky", "vast"}},
		{Value: "浩", Weight: 0.8, Tags: []string{"vast", "grand"}},
		{Value: "輝", Weight: 0.8, Tags: []string{"brilliant", "radiant"}},
		{Value: "賢", Weight: 0.7, Tags: []string{"virtuous", "wise"}},
		{Value: "承", Weight: 0.7, Tags: []string{"inherit", "carry"}},
		{Value: "彥", Weight: 0.7, Tags: []string{"talented", "virtuous"}},
		{Value: "俊", Weight: 0.7, Tags: []string{"talented", "handsome"}},
		{Value: "廷", Weight: 0.6, Tags: []string{"court", "imperial"}},
		{Value: "睿", Weight: 0.6, Tags: []string{"wise", "intelligent"}},
		{Value: "翔", Weight: 0.6, Tags: []string{"soar", "fly"}},
		{Value: "晨", Weight: 0.6, Tags: []string{"morning", "dawn"}},
		{Value: "軒", Weight: 0.6, Tags: []string{"noble", "carriage"}},
		{Value: "安", Weight: 0.5, Tags: []string{"peace", "safety"}},
		{Value: "康", Weight: 0.5, Tags: []string{"health", "prosperity"}},
		{Value: "國", Weight: 0.5, Tags: []string{"country", "nation"}},
		{Value: "成", Weight: 0.5, Tags: []string{"achieve", "complete"}},
		{Value: "峰", Weight: 0.5, Tags: []string{"peak", "summit"}},
		{Value: "豪", Weight: 0.4, Tags: []string{"heroic", "grand"}},
		{Value: "瑋", Weight: 0.4, Tags: []string{"precious", "jade"}},
		{Value: "宸", Weight: 0.4, Tags: []string{"imperial", "palace"}},
		{Value: "祥", Weight: 0.4, Tags: []string{"auspicious", "lucky"}},
		{Value: "鴻", Weight: 0.3, Tags: []string{"swan", "grand"}},
		{Value: "源", Weight: 0.3, Tags: []string{"source", "origin"}},
		{Value: "晟", Weight: 0.3, Tags: []string{"bright", "prosperous"}},
		{Value: "諺", Weight: 0.3, Tags: []string{"proverb", "wise"}},
		{Value: "毅", Weight: 0.3, Tags: []string{"determined", "resolute"}},
		{Value: "維", Weight: 0.3, Tags: []string{"maintain", "preserve"}},
	},
}

var dsZhtw_6 = &DataSet{
	Language: "zh-TW",
	Country:  "TW",
	Type:     "names",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "王", Weight: 3.0, Tags: []string{"common", "royal"}},
		{Value: "李", Weight: 2.8, Tags: []string{"common", "royal"}},
		{Value: "張", Weight: 2.6, Tags: []string{"common"}},
		{Value: "劉", Weight: 2.4, Tags: []string{"common", "royal"}},
		{Value: "陳", Weight: 2.2, Tags: []string{"common"}},
		{Value: "楊", Weight: 2.0, Tags: []string{"common"}},
		{Value: "趙", Weight: 1.8, Tags: []string{"common", "royal"}},
		{Value: "黃", Weight: 1.6, Tags: []string{"common"}},
		{Value: "周", Weight: 1.4, Tags: []string{"common", "royal"}},
		{Value: "吳", Weight: 1.2, Tags: []string{"common"}},
		{Value: "徐", Tags: []string{"common"}},
		{Value: "孫", Tags: []string{"common"}},
		{Value: "胡", Tags: []string{"common"}},
		{Value: "朱", Weight: 0.9, Tags: []string{"common", "royal"}},
		{Value: "高", Weight: 0.9, Tags: []string{"common"}},
		{Value: "林", Weight: 0.9, Tags: []string{"common"}},
		{Value: "何", Weight: 0.8, Tags: []string{"common"}},
		{Value: "郭", Weight: 0.8, Tags: []string{"common"}},
		{Value: "馬", Weight: 0.8, Tags: []string{"common"}},
		{Value: "羅", Weight: 0.7, Tags: []string{"common"}},
		{Value: "梁", Weight: 0.7, Tags: []string{"common"}},
		{Value: "宋", Weight: 0.7, Tags: []string{"common", "royal"}},
		{Value: "鄭", Weight: 0.6, Tags: []string{"common"}},
		{Value: "謝", Weight: 0.6, Tags: []string{"common"}},
		{Value: "韓", Weight: 0.6, Tags: []string{"common"}},
		{Value: "唐", Weight: 0.5, Tags: []string{"common", "royal"}},
		{Value: "馮", Weight: 0.5, Tags: []string{"common"}},
		{Value: "于", Weight: 0.5, Tags: []string{"common"}},
		{Value: "董", Weight: 0.5, Tags: []string{"common"}},
		{Value: "蕭", Weight: 0.4, Tags: []string{"noble"}},
		{Value: "程", Weight: 0.4, Tags: []string{"common"}},
		{Value: "曹", Weight: 0.4, Tags: []string{"common", "royal"}},
		{Value: "袁", Weight: 0.4, Tags: []string{"common"}},
		{Value: "鄧", Weight: 0.4, Tags: []string{"common"}},
		{Value: "許", Weight: 0.4, Tags: []string{"common"}},
		{Value: "傅", Weight: 0.3, Tags: []string{"noble"}},
		{Value: "沈", Weight: 0.3, Tags: []string{"common"}},
		{Value: "曾", Weight: 0.3, Tags: []string{"common"}},
		{Value: "彭", Weight: 0.3, Tags: []string{"common"}},
		{Value: "呂", Weight: 0.3, Tags: []string{"common"}},
		{Value: "蘇", Weight: 0.3, Tags: []string{"common"}},
		{Value: "盧", Weight: 0.3, Tags: []string{"common"}},
		{Value: "蔣", Weight: 0.3, Tags: []string{"common"}},
		{Value: "蔡", Weight: 0.3, Tags: []string{"common"}},
		{Value: "賈", Weight: 0.3, Tags: []string{"common"}},
	},
}

var dsZhtw_7 = &DataSet{
	Language: "zh-TW",
	Type:     "texts",
	Version:  "1.0.0",
	Items: []DataItem{
		{Value: "文本"},
		{Value: "文字", Weight: 0.95},
		{Value: "句子", Weight: 0.9},
		{Value: "段落", Weight: 0.85},
		{Value: "文章", Weight: 0.8},
		{Value: "報告", Weight: 0.75},
		{Value: "研究", Weight: 0.7},
		{Value: "分析", Weight: 0.6499999999999999},
		{Value: "內容", Weight: 0.6},
		{Value: "主題", Weight: 0.55},
		{Value: "概念", Weight: 0.5},
		{Value: "意義", Weight: 0.44999999999999996},
		{Value: "語言", Weight: 0.3999999999999999},
		{Value: "文學", Weight: 0.35},
		{Value: "寫作", Weight: 0.29999999999999993},
	},
}
