package fake

func init() {
	registerDataSet("en", "addresses", "cities", dsEn_0)
	registerDataSet("en", "addresses", "streets", dsEn_1)
	registerDataSet("en", "companies", "names", dsEn_2)
	registerDataSet("en", "companies", "suffixes", dsEn_3)
	registerDataSet("en", "names", "first_female", dsEn_4)
	registerDataSet("en", "names", "first_male", dsEn_5)
	registerDataSet("en", "names", "last", dsEn_6)
	registerDataSet("en", "texts", "lorem", dsEn_7)
}

var dsEn_0 = &DataSet{
	Language: "en",
	Country:  "US",
	Type:     "addresses",
	Version:  "1.0.0",
	Items: []DataItem{
		{Value: "New York", Weight: 2.0, Tags: []string{"major", "east"}, Meta: map[string]string{"state": "NY", "zip_prefix": "10"}},
		{Value: "Los Angeles", Weight: 1.8, Tags: []string{"major", "west"}, Meta: map[string]string{"state": "CA", "zip_prefix": "90"}},
		{Value: "Chicago", Weight: 1.6, Tags: []string{"major", "midwest"}, Meta: map[string]string{"state": "IL", "zip_prefix": "60"}},
		{Value: "Houston", Weight: 1.4, Tags: []string{"major", "south"}, Meta: map[string]string{"state": "TX", "zip_prefix": "77"}},
		{Value: "Phoenix", Weight: 1.2, Tags: []string{"major", "west"}, Meta: map[string]string{"state": "AZ", "zip_prefix": "85"}},
		{Value: "Philadelphia", Tags: []string{"major", "east"}, Meta: map[string]string{"state": "PA", "zip_prefix": "19"}},
		{Value: "San Antonio", Weight: 0.9, Tags: []string{"major", "south"}, Meta: map[string]string{"state": "TX", "zip_prefix": "78"}},
		{Value: "San Diego", Weight: 0.8, Tags: []string{"major", "west"}, Meta: map[string]string{"state": "CA", "zip_prefix": "92"}},
		{Value: "Dallas", Weight: 0.8, Tags: []string{"major", "south"}, Meta: map[string]string{"state": "TX", "zip_prefix": "75"}},
		{Value: "San Jose", Weight: 0.7, Tags: []string{"major", "west"}, Meta: map[string]string{"state": "CA", "zip_prefix": "95"}},
		{Value: "Austin", Weight: 0.7, Tags: []string{"medium", "south"}, Meta: map[string]string{"state": "TX", "zip_prefix": "73"}},
		{Value: "Jacksonville", Weight: 0.6, Tags: []string{"medium", "south"}, Meta: map[string]string{"state": "FL", "zip_prefix": "32"}},
		{Value: "San Francisco", Weight: 0.6, Tags: []string{"major", "west"}, Meta: map[string]string{"state": "CA", "zip_prefix": "94"}},
		{Value: "Columbus", Weight: 0.5, Tags: []string{"medium", "midwest"}, Meta: map[string]string{"state": "OH", "zip_prefix": "43"}},
		{Value: "Fort Worth", Weight: 0.5, Tags: []string{"medium", "south"}, Meta: map[string]string{"state": "TX", "zip_prefix": "76"}},
		{Value: "Indianapolis", Weight: 0.5, Tags: []string{"medium", "midwest"}, Meta: map[string]string{"state": "IN", "zip_prefix": "46"}},
		{Value: "Charlotte", Weight: 0.4, Tags: []string{"medium", "south"}, Meta: map[string]string{"state": "NC", "zip_prefix": "28"}},
		{Value: "Seattle", Weight: 0.4, Tags: []string{"major", "west"}, Meta: map[string]string{"state": "WA", "zip_prefix": "98"}},
		{Value: "Denver", Weight: 0.4, Tags: []string{"medium", "west"}, Meta: map[string]string{"state": "CO", "zip_prefix": "80"}},
		{Value: "Boston", Weight: 0.4, Tags: []string{"major", "east"}, Meta: map[string]string{"state": "MA", "zip_prefix": "02"}},
	},
}

var dsEn_1 = &DataSet{
	Language: "en",
	Type:     "addresses",
	Version:  "1.0.0",
	Items: []DataItem{
		{Value: "Main Street", Weight: 2.0},
		{Value: "Park Avenue", Weight: 1.8},
		{Value: "Oak Street", Weight: 1.6},
		{Value: "Pine Street", Weight: 1.4},
		{Value: "Maple Avenue", Weight: 1.2},
		{Value: "Cedar Street"},
		{Value: "Elm Street"},
		{Value: "Washington Street", Weight: 0.9},
		{Value: "Lake Street", Weight: 0.9},
		{Value: "Hill Street", Weight: 0.8},
		{Value: "Second Street", Weight: 0.8},
		{Value: "Third Street", Weight: 0.7},
		{Value: "First Street", Weight: 0.7},
		{Value: "Fourth Street", Weight: 0.6},
		{Value: "Fifth Street", Weight: 0.6},
		{Value: "Sixth Street", Weight: 0.5},
		{Value: "Seventh Street", Weight: 0.5},
		{Value: "Eighth Street", Weight: 0.4},
		{Value: "Ninth Street", Weight: 0.4},
		{Value: "Tenth Street", Weight: 0.4},
		{Value: "North Street", Weight: 0.6},
		{Value: "South Street", Weight: 0.6},
		{Value: "East Street", Weight: 0.5},
		{Value: "West Street", Weight: 0.5},
		{Value: "Center Street", Weight: 0.7},
		{Value: "Church Street", Weight: 0.6},
		{Value: "Court Street", Weight: 0.5},
		{Value: "High Street", Weight: 0.6},
		{Value: "Spring Street", Weight: 0.5},
		{Value: "Water Street", Weight: 0.5},
		{Value: "Mill Street", Weight: 0.4},
		{Value: "River Street", Weight: 0.4},
		{Value: "School Street", Weight: 0.4},
		{Value: "State Street", Weight: 0.5},
		{Value: "Union Street", Weight: 0.4},
		{Value: "Valley Road", Weight: 0.4},
		{Value: "Walnut Street", Weight: 0.4},
		{Value: "Cherry Street", Weight: 0.3},
		{Value: "Chestnut Street", Weight: 0.3},
		{Value: "Franklin Street", Weight: 0.3},
	},
}

var dsEn_2 = &DataSet{
	Language: "en",
	Type:     "companies",
	Version:  "1.0.0",
	Items: []DataItem{
		{Value: "Google", Weight: 2.0, Tags: []string{"tech", "large"}, Meta: map[string]string{"industry": "technology"}},
		{Value: "Microsoft", Weight: 2.0, Tags: []string{"tech", "large"}, Meta: map[string]string{"industry": "technology"}},
		{Value: "Apple", Weight: 2.0, Tags: []string{"tech", "large"}, Meta: map[string]string{"industry": "technology"}},
		{Value: "Amazon", Weight: 2.0, Tags: []string{"tech", "large"}, Meta: map[string]string{"industry": "ecommerce"}},
		{Value: "Facebook", Weight: 1.8, Tags: []string{"tech", "large"}, Meta: map[string]string{"industry": "social"}},
		{Value: "Netflix", Weight: 1.6, Tags: []string{"tech", "large"}, Meta: map[string]string{"industry": "entertainment"}},
		{Value: "Tesla", Weight: 1.4, Tags: []string{"tech", "automotive"}, Meta: map[string]string{"industry": "automotive"}},
		{Value: "Uber", Weight: 1.2, Tags: []string{"tech", "transport"}, Meta: map[string]string{"industry": "transportation"}},
		{Value: "Airbnb", Tags: []string{"tech", "hospitality"}, Meta: map[string]string{"industry": "hospitality"}},
		{Value: "Spotify", Tags: []string{"tech", "media"}, Meta: map[string]string{"industry": "music"}},
		{Value: "Adobe", Weight: 0.9, Tags: []string{"tech", "software"}, Meta: map[string]string{"industry": "software"}},
		{Value: "Salesforce", Weight: 0.8, Tags: []string{"tech", "enterprise"}, Meta: map[string]string{"industry": "crm"}},
		{Value: "Oracle", Weight: 0.8, Tags: []string{"tech", "enterprise"}, Meta: map[string]string{"industry": "database"}},
		{Value: "IBM", Weight: 0.7, Tags: []string{"tech", "enterprise"}, Meta: map[string]string{"industry": "consulting"}},
		{Value: "Intel", Weight: 0.7, Tags: []string{"tech", "hardware"}, Meta: map[string]string{"industry": "semiconductors"}},
		{Value: "Cisco", Weight: 0.6, Tags: []string{"tech", "networking"}, Meta: map[string]string{"industry": "networking"}},
		{Value: "VMware", Weight: 0.6, Tags: []string{"tech", "enterprise"}, Meta: map[string]string{"industry": "virtualization"}},
		{Value: "PayPal", Weight: 0.6, Tags: []string{"tech", "fintech"}, Meta: map[string]string{"industry": "payments"}},
		{Value: "Square", Weight: 0.5, Tags: []string{"tech", "fintech"}, Meta: map[string]string{"industry": "payments"}},
		{Value: "Stripe", Weight: 0.5, Tags: []string{"tech", "fintech"}, Meta: map[string]string{"industry": "payments"}},
		{Value: "JPMorgan Chase", Weight: 1.5, Tags: []string{"finance", "large"}, Meta: map[string]string{"industry": "banking"}},
		{Value: "Bank of America", Weight: 1.4, Tags: []string{"finance", "large"}, Meta: map[string]string{"industry": "banking"}},
		{Value: "Wells Fargo", Weight: 1.3, Tags: []string{"finance", "large"}, Meta: map[string]string{"industry": "banking"}},
		{Value: "Goldman Sachs", Tags: []string{"finance", "investment"}, Meta: map[string]string{"industry": "investment"}},
		{Value: "Morgan Stanley", Weight: 0.9, Tags: []string{"finance", "investment"}, Meta: map[string]string{"industry": "investment"}},
		{Value: "Walmart", Weight: 2.0, Tags: []string{"retail", "large"}, Meta: map[string]string{"industry": "retail"}},
		{Value: "Target", Tags: []string{"retail", "medium"}, Meta: map[string]string{"industry": "retail"}},
		{Value: "Costco", Weight: 0.9, Tags: []string{"retail", "medium"}, Meta: map[string]string{"industry": "wholesale"}},
		{Value: "Home Depot", Weight: 0.8, Tags: []string{"retail", "medium"}, Meta: map[string]string{"industry": "home_improvement"}},
		{Value: "McDonald's", Weight: 1.5, Tags: []string{"food", "franchise"}, Meta: map[string]string{"industry": "fast_food"}},
		{Value: "Starbucks", Tags: []string{"food", "franchise"}, Meta: map[string]string{"industry": "coffee"}},
		{Value: "Coca-Cola", Weight: 1.2, Tags: []string{"food", "beverage"}, Meta: map[string]string{"industry": "beverages"}},
		{Value: "PepsiCo", Tags: []string{"food", "beverage"}, Meta: map[string]string{"industry": "beverages"}},
		{Value: "General Electric", Tags: []string{"industrial", "large"}, Meta: map[string]string{"industry": "conglomerate"}},
		{Value: "Boeing", Weight: 0.9, Tags: []string{"aerospace", "large"}, Meta: map[string]string{"industry": "aerospace"}},
		{Value: "Ford", Weight: 0.8, Tags: []string{"automotive", "large"}, Meta: map[string]string{"industry": "automotive"}},
		{Value: "General Motors", Weight: 0.7, Tags: []string{"automotive", "large"}, Meta: map[string]string{"industry": "automotive"}},
		{Value: "ExxonMobil", Weight: 0.9, Tags: []string{"energy", "large"}, Meta: map[string]string{"industry": "oil_gas"}},
		{Value: "Chevron", Weight: 0.7, Tags: []string{"energy", "large"}, Meta: map[string]string{"industry": "oil_gas"}},
		{Value: "Johnson & Johnson", Tags: []string{"healthcare", "pharma"}, Meta: map[string]string{"industry": "pharmaceuticals"}},
		{Value: "Pfizer", Weight: 0.9, Tags: []string{"healthcare", "pharma"}, Meta: map[string]string{"industry": "pharmaceuticals"}},
		{Value: "Merck", Weight: 0.8, Tags: []string{"healthcare", "pharma"}, Meta: map[string]string{"industry": "pharmaceuticals"}},
		{Value: "UnitedHealth", Weight: 0.8, Tags: []string{"healthcare", "insurance"}, Meta: map[string]string{"industry": "health_insurance"}},
		{Value: "Verizon", Weight: 0.9, Tags: []string{"telecom", "large"}, Meta: map[string]string{"industry": "telecommunications"}},
		{Value: "AT&T", Weight: 0.8, Tags: []string{"telecom", "large"}, Meta: map[string]string{"industry": "telecommunications"}},
		{Value: "T-Mobile", Weight: 0.7, Tags: []string{"telecom", "medium"}, Meta: map[string]string{"industry": "telecommunications"}},
		{Value: "Comcast", Weight: 0.7, Tags: []string{"media", "telecom"}, Meta: map[string]string{"industry": "cable"}},
		{Value: "Disney", Tags: []string{"entertainment", "media"}, Meta: map[string]string{"industry": "entertainment"}},
		{Value: "Warner Bros", Weight: 0.6, Tags: []string{"entertainment", "media"}, Meta: map[string]string{"industry": "entertainment"}},
		{Value: "Sony", Weight: 0.8, Tags: []string{"tech", "entertainment"}, Meta: map[string]string{"industry": "electronics"}},
		{Value: "Nike", Tags: []string{"apparel", "sports"}, Meta: map[string]string{"industry": "sportswear"}},
	},
}

var dsEn_3 = &DataSet{
	Language: "en",
	Type:     "companies",
	Version:  "1.0.0",
	Items: []DataItem{
		{Value: "Inc.", Weight: 3.0, Tags: []string{"common", "us"}},
		{Value: "LLC", Weight: 2.5, Tags: []string{"common", "us"}},
		{Value: "Corp.", Weight: 2.0, Tags: []string{"common", "us"}},
		{Value: "Co.", Weight: 2.0, Tags: []string{"common", "general"}},
		{Value: "Ltd.", Weight: 1.8, Tags: []string{"common", "uk"}},
		{Value: "Group", Weight: 1.5, Tags: []string{"large", "holding"}},
		{Value: "Holdings", Weight: 1.2, Tags: []string{"large", "holding"}},
		{Value: "Company", Tags: []string{"formal", "general"}},
		{Value: "Corporation", Tags: []string{"formal", "large"}},
		{Value: "Enterprises", Weight: 0.8, Tags: []string{"medium", "general"}},
		{Value: "Industries", Weight: 0.8, Tags: []string{"manufacturing", "industrial"}},
		{Value: "Systems", Weight: 0.7, Tags: []string{"tech", "it"}},
		{Value: "Solutions", Weight: 0.7, Tags: []string{"tech", "consulting"}},
		{Value: "Technologies", Weight: 0.6, Tags: []string{"tech", "innovation"}},
		{Value: "Dynamics", Weight: 0.5, Tags: []string{"tech", "consulting"}},
		{Value: "Associates", Weight: 0.6, Tags: []string{"professional", "consulting"}},
		{Value: "Partners", Weight: 0.6, Tags: []string{"professional", "consulting"}},
		{Value: "Services", Weight: 0.8, Tags: []string{"service", "consulting"}},
		{Value: "Consulting", Weight: 0.5, Tags: []string{"professional", "consulting"}},
		{Value: "Global", Weight: 0.4, Tags: []string{"large", "international"}},
		{Value: "International", Weight: 0.4, Tags: []string{"large", "international"}},
		{Value: "Worldwide", Weight: 0.3, Tags: []string{"large", "international"}},
		{Value: "United", Weight: 0.3, Tags: []string{"large", "general"}},
		{Value: "Universal", Weight: 0.2, Tags: []string{"large", "general"}},
		{Value: "National", Weight: 0.3, Tags: []string{"medium", "general"}},
		{Value: "Regional", Weight: 0.2, Tags: []string{"small", "local"}},
		{Value: "Local", Weight: 0.2, Tags: []string{"small", "local"}},
		{Value: "Express", Weight: 0.3, Tags: []string{"logistics", "fast"}},
		{Value: "Direct", Weight: 0.3, Tags: []string{"service", "direct"}},
		{Value: "Plus", Weight: 0.2, Tags: []string{"service", "premium"}},
		{Value: "Pro", Weight: 0.2, Tags: []string{"service", "professional"}},
		{Value: "Elite", Weight: 0.1, Tags: []string{"service", "premium"}},
		{Value: "Premium", Weight: 0.1, Tags: []string{"service", "premium"}},
		{Value: "Advanced", Weight: 0.2, Tags: []string{"tech", "advanced"}},
		{Value: "Innovation", Weight: 0.1, Tags: []string{"tech", "innovation"}},
		{Value: "Labs", Weight: 0.2, Tags: []string{"tech", "research"}},
		{Value: "Works", Weight: 0.2, Tags: []string{"creative", "manufacturing"}},
		{Value: "Studio", Weight: 0.1, Tags: []string{"creative", "design"}},
		{Value: "Design", Weight: 0.1, Tags: []string{"creative", "design"}},
		{Value: "Media", Weight: 0.2, Tags: []string{"media", "content"}},
		{Value: "Digital", Weight: 0.2, Tags: []string{"tech", "digital"}},
		{Value: "Online", Weight: 0.1, Tags: []string{"tech", "internet"}},
		{Value: "Network", Weight: 0.2, Tags: []string{"tech", "networking"}},
		{Value: "Cloud", Weight: 0.1, Tags: []string{"tech", "cloud"}},
		{Value: "Data", Weight: 0.1, Tags: []string{"tech", "data"}},
		{Value: "Analytics", Weight: 0.1, Tags: []string{"tech", "analytics"}},
		{Value: "Intelligence", Weight: 0.1, Tags: []string{"tech", "ai"}},
		{Value: "Automation", Weight: 0.1, Tags: []string{"tech", "automation"}},
		{Value: "Robotics", Weight: 0.1, Tags: []string{"tech", "robotics"}},
		{Value: "Energy", Weight: 0.2, Tags: []string{"energy", "utilities"}},
		{Value: "Power", Weight: 0.2, Tags: []string{"energy", "utilities"}},
		{Value: "Resources", Weight: 0.2, Tags: []string{"resources", "extraction"}},
		{Value: "Materials", Weight: 0.2, Tags: []string{"manufacturing", "materials"}},
		{Value: "Manufacturing", Weight: 0.2, Tags: []string{"manufacturing", "production"}},
		{Value: "Production", Weight: 0.2, Tags: []string{"manufacturing", "production"}},
		{Value: "Distribution", Weight: 0.2, Tags: []string{"logistics", "distribution"}},
		{Value: "Logistics", Weight: 0.2, Tags: []string{"logistics", "supply_chain"}},
		{Value: "Supply", Weight: 0.1, Tags: []string{"logistics", "supply_chain"}},
		{Value: "Trading", Weight: 0.2, Tags: []string{"finance", "trading"}},
		{Value: "Investment", Weight: 0.2, Tags: []string{"finance", "investment"}},
		{Value: "Capital", Weight: 0.2, Tags: []string{"finance", "investment"}},
		{Value: "Finance", Weight: 0.2, Tags: []string{"finance", "general"}},
		{Value: "Bank", Weight: 0.3, Tags: []string{"finance", "banking"}},
		{Value: "Credit", Weight: 0.2, Tags: []string{"finance", "credit"}},
		{Value: "Insurance", Weight: 0.2, Tags: []string{"finance", "insurance"}},
		{Value: "Real Estate", Weight: 0.2, Tags: []string{"real_estate", "property"}},
		{Value: "Property", Weight: 0.2, Tags: []string{"real_estate", "property"}},
		{Value: "Development", Weight: 0.2, Tags: []string{"real_estate", "development"}},
		{Value: "Construction", Weight: 0.2, Tags: []string{"construction", "building"}},
		{Value: "Engineering", Weight: 0.2, Tags: []string{"engineering", "technical"}},
		{Value: "Architecture", Weight: 0.1, Tags: []string{"architecture", "design"}},
		{Value: "Health", Weight: 0.2, Tags: []string{"healthcare", "medical"}},
		{Value: "Medical", Weight: 0.2, Tags: []string{"healthcare", "medical"}},
		{Value: "Care", Weight: 0.2, Tags: []string{"healthcare", "care"}},
		{Value: "Wellness", Weight: 0.1, Tags: []string{"healthcare", "wellness"}},
		{Value: "Fitness", Weight: 0.1, Tags: []string{"healthcare", "fitness"}},
		{Value: "Education", Weight: 0.2, Tags: []string{"education", "learning"}},
		{Value: "Training", Weight: 0.2, Tags: []string{"education", "training"}},
		{Value: "Learning", Weight: 0.1, Tags: []string{"education", "learning"}},
		{Value: "Academy", Weight: 0.1, Tags: []string{"education", "academy"}},
		{Value: "Institute", Weight: 0.1, Tags: []string{"education", "research"}},
		{Value: "Research", Weight: 0.1, Tags: []string{"research", "academic"}},
		{Value: "Foundation", Weight: 0.1, Tags: []string{"nonprofit", "foundation"}},
		{Value: "Trust", Weight: 0.1, Tags: []string{"finance", "trust"}},
		{Value: "Fund", Weight: 0.1, Tags: []string{"finance", "fund"}},
		{Value: "Ventures", Weight: 0.1, Tags: []string{"investment", "ventures"}},
		{Value: "Equity", Weight: 0.1, Tags: []string{"finance", "equity"}},
		{Value: "Assets", Weight: 0.1, Tags: []string{"finance", "assets"}},
		{Value: "Holdings", Weight: 0.2, Tags: []string{"finance", "holdings"}},
		{Value: "Management", Weight: 0.2, Tags: []string{"service", "management"}},
		{Value: "Advisors", Weight: 0.1, Tags: []string{"consulting", "advisory"}},
		{Value: "Consultants", Weight: 0.1, Tags: []string{"consulting", "advisory"}},
		{Value: "Specialists", Weight: 0.1, Tags: []string{"service", "specialist"}},
		{Value: "Experts", Weight: 0.1, Tags: []string{"service", "expert"}},
		{Value: "Professionals", Weight: 0.1, Tags: []string{"service", "professional"}},
	},
}

var dsEn_4 = &DataSet{
	Language: "en",
	Country:  "US",
	Type:     "names",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "Mary", Weight: 1.5, Tags: []string{"biblical", "traditional"}},
		{Value: "Patricia", Weight: 1.4, Tags: []string{"noble", "traditional"}},
		{Value: "Jennifer", Weight: 1.3, Tags: []string{"modern", "popular"}},
		{Value: "Linda", Weight: 1.2, Tags: []string{"spanish", "popular"}},
		{Value: "Elizabeth", Weight: 1.1, Tags: []string{"royal", "biblical"}},
		{Value: "Barbara", Tags: []string{"traditional", "strong"}},
		{Value: "Susan", Tags: []string{"biblical", "traditional"}},
		{Value: "Jessica", Tags: []string{"literary", "modern"}},
		{Value: "Sarah", Tags: []string{"biblical", "classic"}},
		{Value: "Karen", Weight: 0.9, Tags: []string{"scandinavian", "pure"}},
		{Value: "Nancy", Weight: 0.9, Tags: []string{"traditional", "grace"}},
		{Value: "Lisa", Weight: 0.9, Tags: []string{"modern", "short"}},
		{Value: "Betty", Weight: 0.8, Tags: []string{"traditional", "nickname"}},
		{Value: "Helen", Weight: 0.8, Tags: []string{"greek", "classical"}},
		{Value: "Sandra", Weight: 0.8, Tags: []string{"modern", "defender"}},
		{Value: "Donna", Weight: 0.7, Tags: []string{"italian", "lady"}},
		{Value: "Carol", Weight: 0.7, Tags: []string{"song", "joy"}},
		{Value: "Ruth", Weight: 0.7, Tags: []string{"biblical", "loyal"}},
		{Value: "Sharon", Weight: 0.7, Tags: []string{"biblical", "plain"}},
		{Value: "Michelle", Weight: 0.7, Tags: []string{"french", "godlike"}},
		{Value: "Laura", Weight: 0.6, Tags: []string{"roman", "laurel"}},
		{Value: "Kimberly", Weight: 0.6, Tags: []string{"english", "meadow"}},
		{Value: "Deborah", Weight: 0.6, Tags: []string{"biblical", "bee"}},
		{Value: "Dorothy", Weight: 0.6, Tags: []string{"greek", "gift"}},
		{Value: "Amy", Weight: 0.5, Tags: []string{"french", "beloved"}},
		{Value: "Angela", Weight: 0.5, Tags: []string{"greek", "angel"}},
		{Value: "Ashley", Weight: 0.5, Tags: []string{"english", "nature"}},
		{Value: "Brenda", Weight: 0.5, Tags: []string{"norse", "sword"}},
		{Value: "Emma", Weight: 0.5, Tags: []string{"german", "universal"}},
		{Value: "Olivia", Weight: 0.5, Tags: []string{"latin", "peace"}},
		{Value: "Cynthia", Weight: 0.4, Tags: []string{"greek", "moon"}},
		{Value: "Kathleen", Weight: 0.4, Tags: []string{"irish", "pure"}},
		{Value: "Samantha", Weight: 0.4, Tags: []string{"aramaic", "listener"}},
		{Value: "Marie", Weight: 0.4, Tags: []string{"french", "biblical"}},
		{Value: "Janet", Weight: 0.4, Tags: []string{"scottish", "grace"}},
		{Value: "Catherine", Weight: 0.4, Tags: []string{"greek", "pure"}},
		{Value: "Frances", Weight: 0.4, Tags: []string{"latin", "french"}},
		{Value: "Christine", Weight: 0.4, Tags: []string{"greek", "christian"}},
		{Value: "Debra", Weight: 0.3, Tags: []string{"biblical", "bee"}},
		{Value: "Rachel", Weight: 0.3, Tags: []string{"biblical", "ewe"}},
		{Value: "Carolyn", Weight: 0.3, Tags: []string{"germanic", "song"}},
		{Value: "Virginia", Weight: 0.3, Tags: []string{"latin", "virgin"}},
		{Value: "Maria", Weight: 0.3, Tags: []string{"latin", "biblical"}},
		{Value: "Heather", Weight: 0.3, Tags: []string{"english", "nature"}},
		{Value: "Diane", Weight: 0.3, Tags: []string{"roman", "divine"}},
		{Value: "Julie", Weight: 0.3, Tags: []string{"latin", "youthful"}},
		{Value: "Joyce", Weight: 0.3, Tags: []string{"latin", "joyful"}},
		{Value: "Victoria", Weight: 0.3, Tags: []string{"latin", "victory"}},
	},
}

var dsEn_5 = &DataSet{
	Language: "en",
	Country:  "US",
	Type:     "names",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "James", Weight: 1.5, Tags: []string{"biblical", "classic"}},
		{Value: "Robert", Weight: 1.4, Tags: []string{"germanic", "bright"}},
		{Value: "John", Weight: 1.3, Tags: []string{"biblical", "traditional"}},
		{Value: "Michael", Weight: 1.2, Tags: []string{"biblical", "archangel"}},
		{Value: "William", Weight: 1.1, Tags: []string{"germanic", "royal"}},
		{Value: "David", Tags: []string{"biblical", "king"}},
		{Value: "Richard", Tags: []string{"germanic", "ruler"}},
		{Value: "Joseph", Tags: []string{"biblical", "patriarch"}},
		{Value: "Thomas", Tags: []string{"aramaic", "apostle"}},
		{Value: "Christopher", Weight: 0.9, Tags: []string{"greek", "christian"}},
		{Value: "Charles", Weight: 0.9, Tags: []string{"germanic", "royal"}},
		{Value: "Daniel", Weight: 0.9, Tags: []string{"biblical", "prophet"}},
		{Value: "Matthew", Weight: 0.8, Tags: []string{"biblical", "apostle"}},
		{Value: "Anthony", Weight: 0.8, Tags: []string{"roman", "flourishing"}},
		{Value: "Mark", Weight: 0.8, Tags: []string{"latin", "war"}},
		{Value: "Donald", Weight: 0.7, Tags: []string{"scottish", "ruler"}},
		{Value: "Steven", Weight: 0.7, Tags: []string{"greek", "crown"}},
		{Value: "Paul", Weight: 0.7, Tags: []string{"latin", "apostle"}},
		{Value: "Andrew", Weight: 0.7, Tags: []string{"greek", "apostle"}},
		{Value: "Joshua", Weight: 0.7, Tags: []string{"biblical", "leader"}},
		{Value: "Kenneth", Weight: 0.6, Tags: []string{"scottish", "handsome"}},
		{Value: "Kevin", Weight: 0.6, Tags: []string{"irish", "gentle"}},
		{Value: "Brian", Weight: 0.6, Tags: []string{"celtic", "noble"}},
		{Value: "George", Weight: 0.6, Tags: []string{"greek", "farmer"}},
		{Value: "Timothy", Weight: 0.6, Tags: []string{"greek", "honor"}},
		{Value: "Ronald", Weight: 0.5, Tags: []string{"norse", "ruler"}},
		{Value: "Edward", Weight: 0.5, Tags: []string{"english", "guardian"}},
		{Value: "Jason", Weight: 0.5, Tags: []string{"greek", "healer"}},
		{Value: "Jeffrey", Weight: 0.5, Tags: []string{"germanic", "peace"}},
		{Value: "Ryan", Weight: 0.5, Tags: []string{"irish", "king"}},
		{Value: "Jacob", Weight: 0.5, Tags: []string{"biblical", "patriarch"}},
		{Value: "Gary", Weight: 0.4, Tags: []string{"germanic", "spear"}},
		{Value: "Nicholas", Weight: 0.4, Tags: []string{"greek", "victory"}},
		{Value: "Eric", Weight: 0.4, Tags: []string{"norse", "ruler"}},
		{Value: "Jonathan", Weight: 0.4, Tags: []string{"biblical", "gift"}},
		{Value: "Stephen", Weight: 0.4, Tags: []string{"greek", "crown"}},
		{Value: "Larry", Weight: 0.4, Tags: []string{"latin", "laurel"}},
		{Value: "Justin", Weight: 0.4, Tags: []string{"latin", "just"}},
		{Value: "Scott", Weight: 0.4, Tags: []string{"scottish", "wanderer"}},
		{Value: "Brandon", Weight: 0.3, Tags: []string{"english", "hill"}},
		{Value: "Benjamin", Weight: 0.3, Tags: []string{"biblical", "son"}},
		{Value: "Samuel", Weight: 0.3, Tags: []string{"biblical", "prophet"}},
		{Value: "Gregory", Weight: 0.3, Tags: []string{"greek", "watchful"}},
		{Value: "Alexander", Weight: 0.3, Tags: []string{"greek", "defender"}},
		{Value: "Frank", Weight: 0.3, Tags: []string{"germanic", "free"}},
		{Value: "Raymond", Weight: 0.3, Tags: []string{"germanic", "advisor"}},
		{Value: "Jack", Weight: 0.3, Tags: []string{"english", "nickname"}},
		{Value: "Dennis", Weight: 0.3, Tags: []string{"greek", "follower"}},
		{Value: "Jerry", Weight: 0.3, Tags: []string{"germanic", "spear"}},
		{Value: "Tyler", Weight: 0.3, Tags: []string{"english", "occupation"}},
	},
}

var dsEn_6 = &DataSet{
	Language: "en",
	Country:  "US",
	Type:     "names",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "Smith", Weight: 2.0, Tags: []string{"occupational", "metalworker"}},
		{Value: "Johnson", Weight: 1.8, Tags: []string{"patronymic", "son"}},
		{Value: "Williams", Weight: 1.6, Tags: []string{"patronymic", "son"}},
		{Value: "Brown", Weight: 1.4, Tags: []string{"descriptive", "color"}},
		{Value: "Jones", Weight: 1.3, Tags: []string{"patronymic", "son"}},
		{Value: "Garcia", Weight: 1.2, Tags: []string{"spanish", "bear"}},
		{Value: "Miller", Weight: 1.1, Tags: []string{"occupational", "grain"}},
		{Value: "Davis", Tags: []string{"patronymic", "son"}},
		{Value: "Rodriguez", Tags: []string{"spanish", "patronymic"}},
		{Value: "Martinez", Tags: []string{"spanish", "patronymic"}},
		{Value: "Hernandez", Weight: 0.9, Tags: []string{"spanish", "patronymic"}},
		{Value: "Lopez", Weight: 0.9, Tags: []string{"spanish", "patronymic"}},
		{Value: "Gonzalez", Weight: 0.9, Tags: []string{"spanish", "patronymic"}},
		{Value: "Wilson", Weight: 0.8, Tags: []string{"patronymic", "son"}},
		{Value: "Anderson", Weight: 0.8, Tags: []string{"scandinavian", "patronymic"}},
		{Value: "Thomas", Weight: 0.8, Tags: []string{"patronymic", "twin"}},
		{Value: "Taylor", Weight: 0.7, Tags: []string{"occupational", "tailor"}},
		{Value: "Moore", Weight: 0.7, Tags: []string{"topographic", "moor"}},
		{Value: "Jackson", Weight: 0.7, Tags: []string{"patronymic", "son"}},
		{Value: "Martin", Weight: 0.7, Tags: []string{"roman", "war"}},
		{Value: "Lee", Weight: 0.6, Tags: []string{"topographic", "meadow"}},
		{Value: "Perez", Weight: 0.6, Tags: []string{"spanish", "patronymic"}},
		{Value: "Thompson", Weight: 0.6, Tags: []string{"patronymic", "son"}},
		{Value: "White", Weight: 0.6, Tags: []string{"descriptive", "color"}},
		{Value: "Harris", Weight: 0.6, Tags: []string{"patronymic", "son"}},
		{Value: "Sanchez", Weight: 0.5, Tags: []string{"spanish", "patronymic"}},
		{Value: "Clark", Weight: 0.5, Tags: []string{"occupational", "clerk"}},
		{Value: "Ramirez", Weight: 0.5, Tags: []string{"spanish", "patronymic"}},
		{Value: "Lewis", Weight: 0.5, Tags: []string{"germanic", "famous"}},
		{Value: "Robinson", Weight: 0.5, Tags: []string{"patronymic", "son"}},
		{Value: "Walker", Weight: 0.5, Tags: []string{"occupational", "cloth"}},
		{Value: "Young", Weight: 0.4, Tags: []string{"descriptive", "age"}},
		{Value: "Allen", Weight: 0.4, Tags: []string{"celtic", "handsome"}},
		{Value: "King", Weight: 0.4, Tags: []string{"occupational", "royal"}},
		{Value: "Wright", Weight: 0.4, Tags: []string{"occupational", "craftsman"}},
		{Value: "Scott", Weight: 0.4, Tags: []string{"ethnic", "scottish"}},
		{Value: "Torres", Weight: 0.4, Tags: []string{"spanish", "towers"}},
		{Value: "Nguyen", Weight: 0.4, Tags: []string{"vietnamese", "royal"}},
		{Value: "Hill", Weight: 0.4, Tags: []string{"topographic", "hill"}},
		{Value: "Flores", Weight: 0.3, Tags: []string{"spanish", "flowers"}},
		{Value: "Green", Weight: 0.3, Tags: []string{"descriptive", "color"}},
		{Value: "Adams", Weight: 0.3, Tags: []string{"patronymic", "son"}},
		{Value: "Nelson", Weight: 0.3, Tags: []string{"patronymic", "son"}},
		{Value: "Baker", Weight: 0.3, Tags: []string{"occupational", "bread"}},
		{Value: "Hall", Weight: 0.3, Tags: []string{"topographic", "hall"}},
		{Value: "Rivera", Weight: 0.3, Tags: []string{"spanish", "river"}},
		{Value: "Campbell", Weight: 0.3, Tags: []string{"scottish", "crooked"}},
		{Value: "Mitchell", Weight: 0.3, Tags: []string{"patronymic", "son"}},
		{Value: "Carter", Weight: 0.3, Tags: []string{"occupational", "cart"}},
		{Value: "Roberts", Weight: 0.3, Tags: []string{"patronymic", "son"}},
	},
}

var dsEn_7 = &DataSet{
	Language: "en",
	Type:     "texts",
	Version:  "1.0.0",
	Items: []DataItem{
		{Value: "lorem"},
		{Value: "ipsum"},
		{Value: "dolor"},
		{Value: "sit"},
		{Value: "amet"},
		{Value: "consectetur", Weight: 0.8},
		{Value: "adipiscing", Weight: 0.8},
		{Value: "elit", Weight: 0.8},
		{Value: "sed", Weight: 0.9},
		{Value: "do", Weight: 0.9},
		{Value: "eiusmod", Weight: 0.7},
		{Value: "tempor", Weight: 0.7},
		{Value: "incididunt", Weight: 0.6},
		{Value: "ut", Weight: 0.9},
		{Value: "labore", Weight: 0.8},
		{Value: "et", Weight: 0.9},
		{Value: "dolore", Weight: 0.8},
		{Value: "magna", Weight: 0.8},
		{Value: "aliqua", Weight: 0.7},
		{Value: "enim", Weight: 0.7},
		{Value: "ad", Weight: 0.8},
		{Value: "minim", Weight: 0.6},
		{Value: "veniam", Weight: 0.6},
		{Value: "quis", Weight: 0.7},
		{Value: "nostrud", Weight: 0.5},
		{Value: "exercitation", Weight: 0.4},
		{Value: "ullamco", Weight: 0.4},
		{Value: "laboris", Weight: 0.5},
		{Value: "nisi", Weight: 0.6},
		{Value: "aliquip", Weight: 0.4},
		{Value: "ex", Weight: 0.6},
		{Value: "ea", Weight: 0.6},
		{Value: "commodo", Weight: 0.5},
		{Value: "consequat", Weight: 0.5},
		{Value: "duis", Weight: 0.6},
		{Value: "aute", Weight: 0.5},
		{Value: "irure", Weight: 0.4},
		{Value: "in", Weight: 0.8},
		{Value: "reprehenderit", Weight: 0.3},
		{Value: "voluptate", Weight: 0.4},
		{Value: "velit", Weight: 0.5},
		{Value: "esse", Weight: 0.5},
		{Value: "cillum", Weight: 0.3},
		{Value: "fugiat", Weight: 0.3},
		{Value: "nulla", Weight: 0.5},
		{Value: "pariatur", Weight: 0.3},
		{Value: "excepteur", Weight: 0.3},
		{Value: "sint", Weight: 0.4},
		{Value: "occaecat", Weight: 0.3},
		{Value: "cupidatat", Weight: 0.3},
		{Value: "non", Weight: 0.6},
		{Value: "proident", Weight: 0.3},
		{Value: "sunt", Weight: 0.4},
		{Value: "culpa", Weight: 0.3},
		{Value: "qui", Weight: 0.5},
		{Value: "officia", Weight: 0.3},
		{Value: "deserunt", Weight: 0.3},
		{Value: "mollit", Weight: 0.3},
		{Value: "anim", Weight: 0.3},
		{Value: "id", Weight: 0.5},
		{Value: "est", Weight: 0.5},
		{Value: "laborum", Weight: 0.4},
		{Value: "at", Weight: 0.6},
		{Value: "vero", Weight: 0.4},
		{Value: "eos", Weight: 0.4},
		{Value: "accusamus", Weight: 0.2},
		{Value: "accusantium", Weight: 0.2},
		{Value: "doloremque", Weight: 0.2},
		{Value: "laudantium", Weight: 0.2},
		{Value: "totam", Weight: 0.3},
		{Value: "rem", Weight: 0.3},
		{Value: "aperiam", Weight: 0.2},
		{Value: "eaque", Weight: 0.3},
		{Value: "ipsa", Weight: 0.3},
		{Value: "quae", Weight: 0.3},
		{Value: "ab", Weight: 0.4},
		{Value: "illo", Weight: 0.3},
		{Value: "inventore", Weight: 0.2},
		{Value: "veritatis", Weight: 0.2},
		{Value: "quasi", Weight: 0.3},
		{Value: "architecto", Weight: 0.2},
		{Value: "beatae", Weight: 0.2},
		{Value: "vitae", Weight: 0.3},
		{Value: "dicta", Weight: 0.3},
		{Value: "explicabo", Weight: 0.2},
		{Value: "nemo", Weight: 0.3},
		{Value: "voluptatem", Weight: 0.2},
		{Value: "quia", Weight: 0.3},
		{Value: "voluptas", Weight: 0.2},
		{Value: "aspernatur", Weight: 0.2},
		{Value: "odit", Weight: 0.2},
		{Value: "aut", Weight: 0.4},
		{Value: "fugit", Weight: 0.2},
		{Value: "magni", Weight: 0.2},
		{Value: "dolores", Weight: 0.3},
		{Value: "ratione", Weight: 0.2},
		{Value: "sequi", Weight: 0.2},
		{Value: "nesciunt", Weight: 0.2},
		{Value: "neque", Weight: 0.3},
		{Value: "porro", Weight: 0.2},
		{Value: "quisquam", Weight: 0.2},
		{Value: "dolorem", Weight: 0.3},
		{Value: "magnam", Weight: 0.2},
		{Value: "quaerat", Weight: 0.2},
		{Value: "voluptatibus", Weight: 0.1},
		{Value: "maiores", Weight: 0.2},
		{Value: "alias", Weight: 0.2},
		{Value: "consequatur", Weight: 0.2},
		{Value: "perferendis", Weight: 0.1},
		{Value: "doloribus", Weight: 0.2},
		{Value: "asperiores", Weight: 0.1},
	},
}
