package fake

func init() {
	registerDataSet("zh-CN", "addresses", "cities", dsZhcn_0)
	registerDataSet("zh-CN", "addresses", "streets", dsZhcn_1)
	registerDataSet("zh-CN", "companies", "names", dsZhcn_2)
	registerDataSet("zh-CN", "companies", "suffixes", dsZhcn_3)
	registerDataSet("zh-CN", "names", "first_female", dsZhcn_4)
	registerDataSet("zh-CN", "names", "first_male", dsZhcn_5)
	registerDataSet("zh-CN", "names", "last", dsZhcn_6)
	registerDataSet("zh-CN", "texts", "lorem", dsZhcn_7)
}

var dsZhcn_0 = &DataSet{
	Language: "zh-CN",
	Country:  "CN",
	Type:     "addresses",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "北京市", Weight: 3.0, Tags: []string{"major", "capital", "north"}, Meta: map[string]string{"province": "北京", "zip_prefix": "10", "population": "21542000", "tier": "1"}},
		{Value: "上海市", Weight: 2.8, Tags: []string{"major", "financial", "east"}, Meta: map[string]string{"province": "上海", "zip_prefix": "20", "population": "26317000", "tier": "1"}},
		{Value: "广州市", Weight: 2.6, Tags: []string{"major", "trade", "south"}, Meta: map[string]string{"province": "广东", "zip_prefix": "51", "population": "18676000", "tier": "1"}},
		{Value: "深圳市", Weight: 2.4, Tags: []string{"major", "tech", "south"}, Meta: map[string]string{"province": "广东", "zip_prefix": "51", "population": "17560000", "tier": "1"}},
		{Value: "天津市", Weight: 2.0, Tags: []string{"major", "port", "north"}, Meta: map[string]string{"province": "天津", "zip_prefix": "30", "population": "13866000", "tier": "1"}},
		{Value: "重庆市", Weight: 1.8, Tags: []string{"major", "mountain", "west"}, Meta: map[string]string{"province": "重庆", "zip_prefix": "40", "population": "32124000", "tier": "1"}},
		{Value: "成都市", Weight: 1.6, Tags: []string{"major", "culture", "west"}, Meta: map[string]string{"province": "四川", "zip_prefix": "61", "population": "20938000", "tier": "1"}},
		{Value: "武汉市", Weight: 1.4, Tags: []string{"major", "transport", "central"}, Meta: map[string]string{"province": "湖北", "zip_prefix": "43", "population": "13635000", "tier": "1"}},
		{Value: "西安市", Weight: 1.2, Tags: []string{"major", "historical", "west"}, Meta: map[string]string{"province": "陕西", "zip_prefix": "71", "population": "12952000", "tier": "1"}},
		{Value: "南京市", Tags: []string{"major", "historical", "east"}, Meta: map[string]string{"province": "江苏", "zip_prefix": "21", "population": "9423000", "tier": "1"}},
		{Value: "杭州市", Tags: []string{"major", "tech", "east"}, Meta: map[string]string{"province": "浙江", "zip_prefix": "31", "population": "12281000", "tier": "1"}},
		{Value: "苏州市", Weight: 0.9, Tags: []string{"medium", "industrial", "east"}, Meta: map[string]string{"province": "江苏", "zip_prefix": "21", "population": "12748000", "tier": "1"}},
		{Value: "济南市", Weight: 0.9, Tags: []string{"medium", "provincial", "north"}, Meta: map[string]string{"province": "山东", "zip_prefix": "25", "population": "9202000", "tier": "2"}},
		{Value: "青岛市", Weight: 0.9, Tags: []string{"medium", "coastal", "north"}, Meta: map[string]string{"province": "山东", "zip_prefix": "26", "population": "10071000", "tier": "2"}},
		{Value: "长沙市", Weight: 0.8, Tags: []string{"medium", "entertainment", "central"}, Meta: map[string]string{"province": "湖南", "zip_prefix": "41", "population": "10047000", "tier": "2"}},
		{Value: "郑州市", Weight: 0.8, Tags: []string{"medium", "transport", "central"}, Meta: map[string]string{"province": "河南", "zip_prefix": "45", "population": "12600000", "tier": "2"}},
		{Value: "沈阳市", Weight: 0.7, Tags: []string{"medium", "industrial", "northeast"}, Meta: map[string]string{"province": "辽宁", "zip_prefix": "11", "population": "9070000", "tier": "2"}},
		{Value: "大连市", Weight: 0.7, Tags: []string{"medium", "port", "northeast"}, Meta: map[string]string{"province": "辽宁", "zip_prefix": "11", "population": "7450000", "tier": "2"}},
		{Value: "哈尔滨市", Weight: 0.6, Tags: []string{"medium", "northern", "northeast"}, Meta: map[string]string{"province": "黑龙江", "zip_prefix": "15", "population": "10009000", "tier": "2"}},
		{Value: "昆明市", Weight: 0.6, Tags: []string{"medium", "tourism", "west"}, Meta: map[string]string{"province": "云南", "zip_prefix": "65", "population": "8460000", "tier": "2"}},
		{Value: "合肥市", Weight: 0.5, Tags: []string{"medium", "tech", "central"}, Meta: map[string]string{"province": "安徽", "zip_prefix": "23", "population": "9369000", "tier": "2"}},
		{Value: "福州市", Weight: 0.5, Tags: []string{"medium", "coastal", "southeast"}, Meta: map[string]string{"province": "福建", "zip_prefix": "35", "population": "8291000", "tier": "2"}},
		{Value: "厦门市", Weight: 0.5, Tags: []string{"medium", "tourism", "southeast"}, Meta: map[string]string{"province": "福建", "zip_prefix": "36", "population": "5163000", "tier": "2"}},
		{Value: "南昌市", Weight: 0.4, Tags: []string{"small", "provincial", "central"}, Meta: map[string]string{"province": "江西", "zip_prefix": "33", "population": "6255000", "tier": "3"}},
		{Value: "石家庄市", Weight: 0.4, Tags: []string{"small", "industrial", "north"}, Meta: map[string]string{"province": "河北", "zip_prefix": "05", "population": "11235000", "tier": "3"}},
		{Value: "太原市", Weight: 0.4, Tags: []string{"small", "mining", "north"}, Meta: map[string]string{"province": "山西", "zip_prefix": "03", "population": "5304000", "tier": "3"}},
		{Value: "长春市", Weight: 0.4, Tags: []string{"small", "automotive", "northeast"}, Meta: map[string]string{"province": "吉林", "zip_prefix": "13", "population": "9066000", "tier": "3"}},
		{Value: "南宁市", Weight: 0.4, Tags: []string{"small", "border", "south"}, Meta: map[string]string{"province": "广西", "zip_prefix": "53", "population": "8741000", "tier": "3"}},
		{Value: "海口市", Weight: 0.3, Tags: []string{"small", "tropical", "south"}, Meta: map[string]string{"province": "海南", "zip_prefix": "57", "population": "2873000", "tier": "3"}},
		{Value: "贵阳市", Weight: 0.3, Tags: []string{"small", "mountainous", "west"}, Meta: map[string]string{"province": "贵州", "zip_prefix": "55", "population": "5987000", "tier": "3"}},
		{Value: "兰州市", Weight: 0.3, Tags: []string{"small", "northwestern", "west"}, Meta: map[string]string{"province": "甘肃", "zip_prefix": "73", "population": "4359000", "tier": "3"}},
	},
}

var dsZhcn_1 = &DataSet{
	Language: "zh-CN",
	Country:  "CN",
	Type:     "addresses",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "人民路", Weight: 2.0, Tags: []string{"political", "common", "main"}},
		{Value: "建设路", Weight: 1.8, Tags: []string{"development", "construction"}},
		{Value: "解放路", Weight: 1.6, Tags: []string{"political", "liberation"}},
		{Value: "中山路", Weight: 1.4, Tags: []string{"historical", "memorial"}},
		{Value: "新华路", Weight: 1.2, Tags: []string{"modern", "renewal"}},
		{Value: "北京路", Tags: []string{"geographical", "capital"}},
		{Value: "上海路", Tags: []string{"geographical", "economic"}},
		{Value: "南京路", Weight: 0.9, Tags: []string{"geographical", "historical"}},
		{Value: "广州路", Weight: 0.9, Tags: []string{"geographical", "commercial"}},
		{Value: "天津路", Weight: 0.8, Tags: []string{"geographical", "port"}},
		{Value: "重庆路", Weight: 0.8, Tags: []string{"geographical", "mountain"}},
		{Value: "成都路", Weight: 0.7, Tags: []string{"geographical", "cultural"}},
		{Value: "西安路", Weight: 0.7, Tags: []string{"geographical", "ancient"}},
		{Value: "武汉路", Weight: 0.6, Tags: []string{"geographical", "central"}},
		{Value: "长安街", Weight: 0.6, Tags: []string{"historical", "imperial", "famous"}},
		{Value: "东风路", Weight: 0.5, Tags: []string{"directional", "political"}},
		{Value: "西风路", Weight: 0.5, Tags: []string{"directional"}},
		{Value: "南风路", Weight: 0.4, Tags: []string{"directional"}},
		{Value: "北风路", Weight: 0.4, Tags: []string{"directional"}},
		{Value: "文化路", Weight: 0.6, Tags: []string{"cultural", "education"}},
		{Value: "教育路", Weight: 0.5, Tags: []string{"education", "academic"}},
		{Value: "健康路", Weight: 0.5, Tags: []string{"health", "medical"}},
		{Value: "幸福路", Weight: 0.4, Tags: []string{"aspirational", "happiness"}},
		{Value: "和平路", Weight: 0.6, Tags: []string{"peace", "aspirational"}},
		{Value: "友谊路", Weight: 0.5, Tags: []string{"friendship", "diplomatic"}},
		{Value: "民主路", Weight: 0.4, Tags: []string{"political", "democracy"}},
		{Value: "自由路", Weight: 0.4, Tags: []string{"political", "freedom"}},
		{Value: "光明路", Weight: 0.5, Tags: []string{"aspirational", "bright"}},
		{Value: "胜利路", Weight: 0.5, Tags: []string{"victory", "triumph"}},
		{Value: "工业路", Weight: 0.4, Tags: []string{"industrial", "economic"}},
		{Value: "商业街", Weight: 0.6, Tags: []string{"commercial", "business"}},
		{Value: "步行街", Weight: 0.5, Tags: []string{"pedestrian", "commercial"}},
		{Value: "购物街", Weight: 0.4, Tags: []string{"shopping", "retail"}},
		{Value: "金融街", Weight: 0.4, Tags: []string{"financial", "business"}},
		{Value: "科技路", Weight: 0.5, Tags: []string{"technology", "innovation"}},
		{Value: "创新大道", Weight: 0.4, Tags: []string{"innovation", "modern"}},
		{Value: "发展大道", Weight: 0.4, Tags: []string{"development", "progress"}},
		{Value: "繁荣街", Weight: 0.3, Tags: []string{"prosperity", "aspirational"}},
		{Value: "昌盛路", Weight: 0.3, Tags: []string{"prosperity", "flourishing"}},
		{Value: "兴华路", Weight: 0.3, Tags: []string{"revival", "china"}},
	},
}

var dsZhcn_2 = &DataSet{
	Language: "zh-CN",
	Country:  "CN",
	Type:     "companies",
	Version:  "1.0.0",
	Items: []DataItem{
		{Value: "腾讯", Weight: 3.0, Tags: []string{"tech", "internet"}, Meta: map[string]string{"industry": "technology", "founded": "1998"}},
		{Value: "阿里巴巴", Weight: 2.9, Tags: []string{"tech", "ecommerce"}, Meta: map[string]string{"industry": "technology", "founded": "1999"}},
		{Value: "百度", Weight: 2.7, Tags: []string{"tech", "search"}, Meta: map[string]string{"industry": "technology", "founded": "2000"}},
		{Value: "华为", Weight: 2.6, Tags: []string{"tech", "telecom"}, Meta: map[string]string{"industry": "technology", "founded": "1987"}},
		{Value: "小米", Weight: 2.4, Tags: []string{"tech", "mobile"}, Meta: map[string]string{"industry": "technology", "founded": "2010"}},
		{Value: "字节跳动", Weight: 2.3, Tags: []string{"tech", "social"}, Meta: map[string]string{"industry": "technology", "founded": "2012"}},
		{Value: "美团", Weight: 2.1, Tags: []string{"tech", "delivery"}, Meta: map[string]string{"industry": "technology", "founded": "2010"}},
		{Value: "京东", Weight: 2.0, Tags: []string{"tech", "ecommerce"}, Meta: map[string]string{"industry": "technology", "founded": "1998"}},
		{Value: "网易", Weight: 1.8, Tags: []string{"tech", "gaming"}, Meta: map[string]string{"industry": "technology", "founded": "1997"}},
		{Value: "新浪", Weight: 1.6, Tags: []string{"tech", "media"}, Meta: map[string]string{"industry": "technology", "founded": "1998"}},
		{Value: "搜狐", Weight: 1.5, Tags: []string{"tech", "portal"}, Meta: map[string]string{"industry": "technology", "founded": "1996"}},
		{Value: "中国移动", Weight: 1.4, Tags: []string{"telecom", "state"}, Meta: map[string]string{"industry": "telecommunications", "founded": "1997"}},
		{Value: "中国联通", Weight: 1.3, Tags: []string{"telecom", "state"}, Meta: map[string]string{"industry": "telecommunications", "founded": "1994"}},
		{Value: "中国电信", Weight: 1.2, Tags: []string{"telecom", "state"}, Meta: map[string]string{"industry": "telecommunications", "founded": "2002"}},
		{Value: "工商银行", Weight: 1.1, Tags: []string{"finance", "banking"}, Meta: map[string]string{"industry": "finance", "founded": "1984"}},
		{Value: "建设银行", Tags: []string{"finance", "banking"}, Meta: map[string]string{"industry": "finance", "founded": "1954"}},
		{Value: "农业银行", Tags: []string{"finance", "banking"}, Meta: map[string]string{"industry": "finance", "founded": "1951"}},
		{Value: "中国银行", Weight: 0.9, Tags: []string{"finance", "banking"}, Meta: map[string]string{"industry": "finance", "founded": "1912"}},
		{Value: "招商银行", Weight: 0.8, Tags: []string{"finance", "banking"}, Meta: map[string]string{"industry": "finance", "founded": "1987"}},
		{Value: "平安银行", Weight: 0.7, Tags: []string{"finance", "banking"}, Meta: map[string]string{"industry": "finance", "founded": "1995"}},
		{Value: "中石油", Weight: 0.9, Tags: []string{"energy", "oil"}, Meta: map[string]string{"industry": "energy", "founded": "1988"}},
		{Value: "中石化", Weight: 0.8, Tags: []string{"energy", "oil"}, Meta: map[string]string{"industry": "energy", "founded": "1998"}},
		{Value: "国家电网", Weight: 0.7, Tags: []string{"energy", "electricity"}, Meta: map[string]string{"industry": "energy", "founded": "2002"}},
		{Value: "海尔", Weight: 0.6, Tags: []string{"appliance", "manufacturing"}, Meta: map[string]string{"industry": "manufacturing", "founded": "1984"}},
		{Value: "格力", Weight: 0.6, Tags: []string{"appliance", "manufacturing"}, Meta: map[string]string{"industry": "manufacturing", "founded": "1991"}},
		{Value: "美的", Weight: 0.6, Tags: []string{"appliance", "manufacturing"}, Meta: map[string]string{"industry": "manufacturing", "founded": "1968"}},
		{Value: "万科", Weight: 0.5, Tags: []string{"realestate", "construction"}, Meta: map[string]string{"industry": "real_estate", "founded": "1984"}},
		{Value: "恒大", Weight: 0.5, Tags: []string{"realestate", "construction"}, Meta: map[string]string{"industry": "real_estate", "founded": "1996"}},
		{Value: "碧桂园", Weight: 0.5, Tags: []string{"realestate", "construction"}, Meta: map[string]string{"industry": "real_estate", "founded": "1992"}},
		{Value: "华润", Weight: 0.4, Tags: []string{"conglomerate", "retail"}, Meta: map[string]string{"industry": "conglomerate", "founded": "1938"}},
		{Value: "中粮集团", Weight: 0.4, Tags: []string{"food", "agriculture"}, Meta: map[string]string{"industry": "food", "founded": "1949"}},
		{Value: "五粮液", Weight: 0.4, Tags: []string{"beverage", "alcohol"}, Meta: map[string]string{"industry": "beverage", "founded": "1959"}},
		{Value: "茅台", Weight: 0.4, Tags: []string{"beverage", "alcohol"}, Meta: map[string]string{"industry": "beverage", "founded": "1951"}},
		{Value: "联想", Weight: 0.4, Tags: []string{"tech", "computer"}, Meta: map[string]string{"industry": "technology", "founded": "1984"}},
		{Value: "比亚迪", Weight: 0.3, Tags: []string{"automotive", "battery"}, Meta: map[string]string{"industry": "automotive", "founded": "1995"}},
	},
}

var dsZhcn_3 = &DataSet{
	Language: "zh",
	Country:  "CN",
	Type:     "companies",
	Version:  "1.0.0",
	Items: []DataItem{
		{Value: "有限公司", Weight: 3.0, Tags: []string{"common", "limited"}},
		{Value: "股份有限公司", Weight: 2.5, Tags: []string{"common", "corporation"}},
		{Value: "集团", Weight: 2.0, Tags: []string{"large", "group"}},
		{Value: "控股", Weight: 1.8, Tags: []string{"holding", "investment"}},
		{Value: "科技", Weight: 1.6, Tags: []string{"technology", "modern"}},
		{Value: "实业", Weight: 1.4, Tags: []string{"industrial", "manufacturing"}},
		{Value: "贸易", Weight: 1.2, Tags: []string{"trading", "commerce"}},
		{Value: "投资", Tags: []string{"investment", "financial"}},
		{Value: "发展", Weight: 0.9, Tags: []string{"development", "growth"}},
		{Value: "建设", Weight: 0.8, Tags: []string{"construction", "infrastructure"}},
	},
}

var dsZhcn_4 = &DataSet{
	Language: "zh-CN",
	Country:  "CN",
	Type:     "names",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "芳", Weight: 2.0, Tags: []string{"traditional", "popular"}},
		{Value: "娜", Weight: 1.9, Tags: []string{"modern", "popular"}},
		{Value: "敏", Weight: 1.8, Tags: []string{"smart", "agile"}},
		{Value: "静", Weight: 1.7, Tags: []string{"peaceful", "elegant"}},
		{Value: "丽", Weight: 1.6, Tags: []string{"beautiful"}},
		{Value: "秀", Weight: 1.5, Tags: []string{"elegant", "beautiful"}},
		{Value: "艳", Weight: 1.4, Tags: []string{"beautiful", "bright"}},
		{Value: "霞", Weight: 1.3, Tags: []string{"nature", "sunset"}},
		{Value: "玲", Weight: 1.2, Tags: []string{"elegant", "delicate"}},
		{Value: "燕", Weight: 1.1, Tags: []string{"nature", "graceful"}},
		{Value: "美", Tags: []string{"beautiful"}},
		{Value: "英", Tags: []string{"heroic", "outstanding"}},
		{Value: "琳", Tags: []string{"precious", "jade"}},
		{Value: "莉", Weight: 0.9, Tags: []string{"flower", "jasmine"}},
		{Value: "欣", Weight: 0.9, Tags: []string{"happy", "joyful"}},
		{Value: "蓉", Weight: 0.9, Tags: []string{"flower", "lotus"}},
		{Value: "雪", Weight: 0.8, Tags: []string{"pure", "nature", "winter"}},
		{Value: "梅", Weight: 0.8, Tags: []string{"flower", "winter", "resilient"}},
		{Value: "兰", Weight: 0.8, Tags: []string{"flower", "elegant", "orchid"}},
		{Value: "菊", Weight: 0.7, Tags: []string{"flower", "autumn"}},
		{Value: "凤", Weight: 0.7, Tags: []string{"mythical", "phoenix"}},
		{Value: "玉", Weight: 0.7, Tags: []string{"precious", "jade"}},
		{Value: "萍", Weight: 0.6, Tags: []string{"nature", "water"}},
		{Value: "红", Weight: 0.6, Tags: []string{"color", "lucky", "red"}},
		{Value: "月", Weight: 0.6, Tags: []string{"nature", "romantic", "moon"}},
		{Value: "晶", Weight: 0.5, Tags: []string{"crystal", "bright"}},
		{Value: "慧", Weight: 0.5, Tags: []string{"wise", "intelligent"}},
		{Value: "婷", Weight: 0.5, Tags: []string{"graceful", "elegant"}},
		{Value: "洁", Weight: 0.5, Tags: []string{"pure", "clean"}},
		{Value: "颖", Weight: 0.5, Tags: []string{"smart", "outstanding"}},
		{Value: "怡", Weight: 0.4, Tags: []string{"pleasant", "happy"}},
		{Value: "雯", Weight: 0.4, Tags: []string{"clouds", "sky"}},
		{Value: "晴", Weight: 0.4, Tags: []string{"sunny", "clear"}},
		{Value: "露", Weight: 0.4, Tags: []string{"nature", "fresh", "dew"}},
		{Value: "薇", Weight: 0.4, Tags: []string{"flower", "rose"}},
		{Value: "倩", Weight: 0.4, Tags: []string{"beautiful", "charming"}},
		{Value: "妍", Weight: 0.3, Tags: []string{"beautiful", "lovely"}},
		{Value: "瑜", Weight: 0.3, Tags: []string{"precious", "jade"}},
		{Value: "嫣", Weight: 0.3, Tags: []string{"beautiful", "charming"}},
		{Value: "璐", Weight: 0.3, Tags: []string{"precious", "jade"}},
		{Value: "琪", Weight: 0.3, Tags: []string{"precious", "jade"}},
		{Value: "瑶", Weight: 0.3, Tags: []string{"precious", "mythical", "jade"}},
		{Value: "馨", Weight: 0.3, Tags: []string{"fragrant", "sweet"}},
		{Value: "雅", Weight: 0.3, Tags: []string{"elegant", "refined"}},
		{Value: "茹", Weight: 0.3, Tags: []string{"gentle", "soft"}},
		{Value: "涵", Weight: 0.3, Tags: []string{"cultivated", "inclusive"}},
		{Value: "诗", Weight: 0.3, Tags: []string{"literary", "poetic"}},
		{Value: "语", Weight: 0.3, Tags: []string{"communication", "speech"}},
		{Value: "心", Weight: 0.3, Tags: []string{"pure", "simple", "heart"}},
		{Value: "妙", Weight: 0.3, Tags: []string{"wonderful", "amazing"}},
		{Value: "思", Weight: 0.3, Tags: []string{"thoughtful", "thinking"}},
	},
}

var dsZhcn_5 = &DataSet{
	Language: "zh-CN",
	Country:  "CN",
	Type:     "names",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "伟", Weight: 2.0, Tags: []string{"great", "mighty"}},
		{Value: "强", Weight: 1.8, Tags: []string{"strong", "powerful"}},
		{Value: "明", Weight: 1.6, Tags: []string{"bright", "intelligent"}},
		{Value: "军", Weight: 1.4, Tags: []string{"military", "soldier"}},
		{Value: "杰", Weight: 1.3, Tags: []string{"outstanding", "hero"}},
		{Value: "磊", Weight: 1.2, Tags: []string{"stone", "upright"}},
		{Value: "超", Weight: 1.1, Tags: []string{"exceed", "transcend"}},
		{Value: "飞", Tags: []string{"fly", "soar"}},
		{Value: "勇", Tags: []string{"brave", "courageous"}},
		{Value: "涛", Tags: []string{"wave", "surge"}},
		{Value: "辉", Weight: 0.9, Tags: []string{"brilliant", "radiant"}},
		{Value: "鹏", Weight: 0.9, Tags: []string{"mythical", "giant"}},
		{Value: "华", Weight: 0.9, Tags: []string{"splendid", "china"}},
		{Value: "斌", Weight: 0.8, Tags: []string{"refined", "cultured"}},
		{Value: "龙", Weight: 0.8, Tags: []string{"dragon", "imperial"}},
		{Value: "凯", Weight: 0.8, Tags: []string{"triumph", "victory"}},
		{Value: "浩", Weight: 0.7, Tags: []string{"vast", "grand"}},
		{Value: "东", Weight: 0.7, Tags: []string{"east", "direction"}},
		{Value: "博", Weight: 0.7, Tags: []string{"learned", "extensive"}},
		{Value: "宇", Weight: 0.7, Tags: []string{"universe", "space"}},
		{Value: "轩", Weight: 0.6, Tags: []string{"noble", "carriage"}},
		{Value: "睿", Weight: 0.6, Tags: []string{"wise", "intelligent"}},
		{Value: "豪", Weight: 0.6, Tags: []string{"heroic", "grand"}},
		{Value: "阳", Weight: 0.6, Tags: []string{"sun", "positive"}},
		{Value: "昊", Weight: 0.6, Tags: []string{"sky", "vast"}},
		{Value: "天", Weight: 0.5, Tags: []string{"heaven", "sky"}},
		{Value: "文", Weight: 0.5, Tags: []string{"culture", "literary"}},
		{Value: "建", Weight: 0.5, Tags: []string{"build", "establish"}},
		{Value: "国", Weight: 0.5, Tags: []string{"country", "nation"}},
		{Value: "峰", Weight: 0.5, Tags: []string{"peak", "summit"}},
		{Value: "志", Weight: 0.5, Tags: []string{"will", "ambition"}},
		{Value: "刚", Weight: 0.4, Tags: []string{"firm", "strong"}},
		{Value: "庆", Weight: 0.4, Tags: []string{"celebrate", "rejoice"}},
		{Value: "成", Weight: 0.4, Tags: []string{"achieve", "complete"}},
		{Value: "林", Weight: 0.4, Tags: []string{"forest", "nature"}},
		{Value: "康", Weight: 0.4, Tags: []string{"health", "prosperity"}},
		{Value: "宁", Weight: 0.4, Tags: []string{"peaceful", "serene"}},
		{Value: "安", Weight: 0.4, Tags: []string{"peace", "safety"}},
		{Value: "胜", Weight: 0.4, Tags: []string{"victory", "triumph"}},
		{Value: "鸿", Weight: 0.3, Tags: []string{"swan", "grand"}},
		{Value: "晨", Weight: 0.3, Tags: []string{"morning", "dawn"}},
		{Value: "翔", Weight: 0.3, Tags: []string{"soar", "fly"}},
		{Value: "思", Weight: 0.3, Tags: []string{"think", "consider"}},
		{Value: "程", Weight: 0.3, Tags: []string{"journey", "process"}},
		{Value: "远", Weight: 0.3, Tags: []string{"distant", "far"}},
		{Value: "源", Weight: 0.3, Tags: []string{"source", "origin"}},
		{Value: "宸", Weight: 0.3, Tags: []string{"imperial", "palace"}},
		{Value: "晟", Weight: 0.3, Tags: []string{"bright", "prosperous"}},
		{Value: "锦", Weight: 0.3, Tags: []string{"brocade", "beautiful"}},
		{Value: "墨", Weight: 0.3, Tags: []string{"ink", "literary"}},
	},
}

var dsZhcn_6 = &DataSet{
	Language: "zh-CN",
	Country:  "CN",
	Type:     "names",
	Version:  "2.0.0",
	Items: []DataItem{
		{Value: "王", Weight: 3.0, Tags: []string{"common", "royal"}},
		{Value: "李", Weight: 2.8, Tags: []string{"common", "royal"}},
		{Value: "张", Weight: 2.6, Tags: []string{"common"}},
		{Value: "刘", Weight: 2.4, Tags: []string{"common", "royal"}},
		{Value: "陈", Weight: 2.2, Tags: []string{"common"}},
		{Value: "杨", Weight: 2.0, Tags: []string{"common"}},
		{Value: "赵", Weight: 1.8, Tags: []string{"common", "royal"}},
		{Value: "黄", Weight: 1.6, Tags: []string{"common"}},
		{Value: "周", Weight: 1.4, Tags: []string{"common", "royal"}},
		{Value: "吴", Weight: 1.2, Tags: []string{"common"}},
		{Value: "徐", Tags: []string{"common"}},
		{Value: "孙", Tags: []string{"common"}},
		{Value: "胡", Tags: []string{"common"}},
		{Value: "朱", Weight: 0.9, Tags: []string{"common", "royal"}},
		{Value: "高", Weight: 0.9, Tags: []string{"common"}},
		{Value: "林", Weight: 0.9, Tags: []string{"common"}},
		{Value: "何", Weight: 0.8, Tags: []string{"common"}},
		{Value: "郭", Weight: 0.8, Tags: []string{"common"}},
		{Value: "马", Weight: 0.8, Tags: []string{"common"}},
		{Value: "罗", Weight: 0.7, Tags: []string{"common"}},
		{Value: "梁", Weight: 0.7, Tags: []string{"common"}},
		{Value: "宋", Weight: 0.7, Tags: []string{"common", "royal"}},
		{Value: "郑", Weight: 0.6, Tags: []string{"common"}},
		{Value: "谢", Weight: 0.6, Tags: []string{"common"}},
		{Value: "韩", Weight: 0.6, Tags: []string{"common"}},
		{Value: "唐", Weight: 0.5, Tags: []string{"common", "royal"}},
		{Value: "冯", Weight: 0.5, Tags: []string{"common"}},
		{Value: "于", Weight: 0.5, Tags: []string{"common"}},
		{Value: "董", Weight: 0.5, Tags: []string{"common"}},
		{Value: "萧", Weight: 0.4, Tags: []string{"noble"}},
		{Value: "程", Weight: 0.4, Tags: []string{"common"}},
		{Value: "曹", Weight: 0.4, Tags: []string{"common", "royal"}},
		{Value: "袁", Weight: 0.4, Tags: []string{"common"}},
		{Value: "邓", Weight: 0.4, Tags: []string{"common"}},
		{Value: "许", Weight: 0.4, Tags: []string{"common"}},
		{Value: "傅", Weight: 0.3, Tags: []string{"noble"}},
		{Value: "沈", Weight: 0.3, Tags: []string{"common"}},
		{Value: "曾", Weight: 0.3, Tags: []string{"common"}},
		{Value: "彭", Weight: 0.3, Tags: []string{"common"}},
		{Value: "吕", Weight: 0.3, Tags: []string{"common"}},
		{Value: "苏", Weight: 0.3, Tags: []string{"common"}},
		{Value: "卢", Weight: 0.3, Tags: []string{"common"}},
		{Value: "蒋", Weight: 0.3, Tags: []string{"common"}},
		{Value: "蔡", Weight: 0.3, Tags: []string{"common"}},
		{Value: "贾", Weight: 0.3, Tags: []string{"common"}},
		{Value: "丁", Weight: 0.2, Tags: []string{"common"}},
		{Value: "魏", Weight: 0.2, Tags: []string{"common", "royal"}},
		{Value: "薛", Weight: 0.2, Tags: []string{"common"}},
		{Value: "叶", Weight: 0.2, Tags: []string{"common"}},
		{Value: "阎", Weight: 0.2, Tags: []string{"common"}},
		{Value: "余", Weight: 0.2, Tags: []string{"common"}},
		{Value: "潘", Weight: 0.2, Tags: []string{"common"}},
		{Value: "杜", Weight: 0.2, Tags: []string{"common"}},
		{Value: "戴", Weight: 0.2, Tags: []string{"common"}},
		{Value: "夏", Weight: 0.2, Tags: []string{"common", "royal"}},
		{Value: "钟", Weight: 0.2, Tags: []string{"common"}},
		{Value: "汪", Weight: 0.2, Tags: []string{"common"}},
		{Value: "田", Weight: 0.2, Tags: []string{"common"}},
		{Value: "任", Weight: 0.2, Tags: []string{"common"}},
		{Value: "姜", Weight: 0.2, Tags: []string{"common"}},
	},
}

var dsZhcn_7 = &DataSet{
	Language: "zh-CN",
	Type:     "texts",
	Version:  "1.0.0",
	Items: []DataItem{
		{Value: "文本"},
		{Value: "文字", Weight: 0.95},
		{Value: "句子", Weight: 0.9},
		{Value: "段落", Weight: 0.85},
		{Value: "文章", Weight: 0.8},
		{Value: "报告", Weight: 0.75},
		{Value: "研究", Weight: 0.7},
		{Value: "分析", Weight: 0.6499999999999999},
		{Value: "内容", Weight: 0.6},
		{Value: "主题", Weight: 0.55},
		{Value: "概念", Weight: 0.5},
		{Value: "意义", Weight: 0.44999999999999996},
		{Value: "语言", Weight: 0.3999999999999999},
		{Value: "文学", Weight: 0.35},
		{Value: "写作", Weight: 0.29999999999999993},
	},
}
