package fake

import (
	xlanguage "golang.org/x/text/language"
)

// langEn is the canonical language tag used to key English pools inside
// [localeUS]. It mirrors the value returned by
// [country.Country.OfficialLanguage] so map lookups always resolve.
var langEn = xlanguage.English

func init() {
	localeUS.LastNames[langEn] = englishLastNames
	localeUS.FirstNames[langEn] = map[Gender][]string{
		GenderMale:   englishMaleFirstNames,
		GenderFemale: englishFemaleFirstNames,
	}
	localeUS.Cities[langEn] = englishCities
	localeUS.Streets[langEn] = englishStreets
}

// englishLastNames is a curated pool of common surnames in the United States
// drawn from the U.S. Census Bureau frequency tables. Used for English-locale
// last-name generation.
var englishLastNames = []string{
	"Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez",
	"Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
	"Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson",
	"Walker", "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores",
	"Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", "Carter", "Roberts",
	"Gomez", "Phillips", "Evans", "Turner", "Diaz", "Parker", "Cruz", "Edwards", "Collins", "Reyes",
	"Stewart", "Morris", "Morales", "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper",
	"Peterson", "Bailey", "Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward", "Richardson",
	"Watson", "Brooks", "Chavez", "Wood", "James", "Bennett", "Gray", "Mendoza", "Ruiz", "Hughes",
	"Price", "Alvarez", "Castillo", "Sanders", "Patel", "Myers", "Long", "Ross", "Foster", "Jimenez",
	"Powell", "Jenkins", "Perry", "Russell", "Sullivan", "Bell", "Coleman", "Butler", "Henderson", "Barnes",
	"Gonzales", "Fisher", "Vasquez", "Simmons", "Romero", "Jordan", "Patterson", "Alexander", "Hamilton", "Graham",
	"Reynolds", "Griffin", "Wallace", "Moreno", "West", "Cole", "Hayes", "Bryant", "Herrera", "Gibson",
	"Ellis", "Tran", "Medina", "Aguilar", "Stevens", "Murray", "Ford", "Castro", "Marshall", "Owens",
	"Harrison", "Fernandez", "McDonald", "Woods", "Washington", "Kennedy", "Wells", "Vargas", "Henry", "Chen",
	"Freeman", "Webb", "Tucker", "Guzman", "Burns", "Crawford", "Olson", "Simpson", "Porter", "Hunter",
	"Gordon", "Mendez", "Silva", "Shaw", "Snyder", "Mason", "Dixon", "Munoz", "Hunt", "Hicks",
	"Holmes", "Palmer", "Wagner", "Black", "Robertson", "Boyd", "Rose", "Stone", "Salazar", "Fox",
	"Warren", "Mills", "Meyer", "Rice", "Schmidt", "Garza", "Daniels", "Ferguson", "Nichols", "Stephens",
	"Soto", "Weaver", "Ryan", "Gardner", "Payne", "Grant", "Dunn", "Kelley", "Spencer", "Hawkins",
	"Arnold", "Pierce", "Vazquez", "Hansen", "Peters", "Santos", "Hart", "Bradley", "Knight", "Elliott",
	"Cunningham", "Duncan", "Armstrong", "Hudson", "Carroll", "Lane", "Riley", "Andrews", "Alvarado", "Ray",
	"Delgado", "Berry", "Perkins", "Hoffman", "Johnston", "Matthews", "Pena", "Richards", "Contreras", "Willis",
	"Carpenter", "Lawrence", "Sandoval", "Guerrero", "George", "Chapman", "Rios", "Estrada", "Ortega", "Watkins",
	"Greene", "Nunez", "Wheeler", "Valdez", "Harper", "Burke", "Larson", "Santiago", "Maldonado", "Morrison",
	"Franklin", "Carlson", "Austin", "Dominguez", "Carr", "Lawson", "Jacobs", "O'Brien", "Lynch", "Singh",
	"Vega", "Bishop", "Montgomery", "Oliver", "Jensen", "Harvey", "Williamson", "Gilbert", "Dean", "Sims",
	"Espinoza", "Howell", "Li", "Wong", "Reid", "Hanson", "Le", "McCoy", "Garrett", "Burton",
	"Fuller", "Wang", "Weber", "Welch", "Rojas", "Lucas", "Marquez", "Fields", "Park", "Yang",
	"Little", "Banks", "Padilla", "Day", "Walsh", "Bowman", "Schultz", "Luna", "Fowler", "Mejia",
	"Davidson", "Acosta", "Brewer", "May", "Holland", "Juarez", "Newman", "Pearson", "Curtis", "Cortez",
	"Douglas", "Schneider", "Joseph", "Barrett", "Navarro", "Figueroa", "Keller", "Avila", "Wade", "Molina",
}

// englishMaleFirstNames is a curated pool of common male first names in the
// United States drawn from the Social Security Administration baby name
// historical tables.
var englishMaleFirstNames = []string{
	"James", "Robert", "John", "Michael", "David", "William", "Richard", "Joseph", "Thomas", "Christopher",
	"Charles", "Daniel", "Matthew", "Anthony", "Mark", "Donald", "Steven", "Andrew", "Paul", "Joshua",
	"Kenneth", "Kevin", "Brian", "George", "Timothy", "Ronald", "Jason", "Edward", "Jeffrey", "Ryan",
	"Jacob", "Gary", "Nicholas", "Eric", "Jonathan", "Stephen", "Larry", "Justin", "Scott", "Brandon",
	"Benjamin", "Samuel", "Gregory", "Frank", "Alexander", "Raymond", "Patrick", "Jack", "Dennis", "Jerry",
	"Tyler", "Aaron", "Jose", "Adam", "Henry", "Nathan", "Douglas", "Zachary", "Peter", "Kyle",
	"Walter", "Ethan", "Jeremy", "Harold", "Keith", "Christian", "Roger", "Noah", "Gerald", "Carl",
	"Terry", "Sean", "Austin", "Arthur", "Lawrence", "Jesse", "Dylan", "Bryan", "Joe", "Jordan",
	"Billy", "Bruce", "Albert", "Willie", "Gabriel", "Logan", "Alan", "Juan", "Wayne", "Roy",
	"Ralph", "Randy", "Eugene", "Vincent", "Russell", "Elijah", "Louis", "Bobby", "Philip", "Johnny",
	"Liam", "Mason", "Lucas", "Oliver", "Aiden", "Carter", "Owen", "Wyatt", "Connor", "Hunter",
	"Caleb", "Isaac", "Jaxon", "Levi", "Eli", "Landon", "Cameron", "Jayden", "Easton", "Asher",
	"Grayson", "Leo", "Julian", "Hudson", "Lincoln", "Charlie", "Theodore", "Jaxson", "Mateo", "Tristan",
	"Adrian", "Cooper", "Anthony", "Chase", "Bentley", "Sebastian", "Dominic", "Xavier", "Tucker", "Brody",
	"Roman", "Maverick", "Parker", "Bryson", "Ezra", "Damian", "Carson", "Brayden", "Nolan", "Ian",
	"Brantley", "Maxwell", "Diego", "Miles", "Jameson", "Jace", "Jeremiah", "Beckett", "Jasper", "Ryker",
	"Greyson", "Declan", "Holden", "Luca", "Bennett", "Silas", "Weston", "Everett", "Kingston", "Atlas",
	"Knox", "Kai", "Axel", "Luka", "Bryce", "Tanner", "Trevor", "Hayden", "Spencer", "Garrett",
	"Cole", "Cody", "Devin", "Marcus", "Travis", "Shane", "Erik", "Phillip", "Curtis", "Todd",
	"Antonio", "Earl", "Stanley", "Leonard", "Nathaniel", "Manuel", "Rodney", "Mario", "Leon", "Francis",
	"Micheal", "Marvin", "Wesley", "Herbert", "Allen", "Lewis", "Theodore", "Joel", "Edwin", "Don",
	"Eddie", "Ricky", "Troy", "Randall", "Barry", "Alexander", "Bernard", "Mike", "Clifford", "Warren",
	"Tony", "Reginald", "Neil", "Cesar", "Jay", "Glenn", "Dean", "Tom", "Calvin", "Derek",
	"Lance", "Lloyd", "Erik", "Darrell", "Marshall", "Allan", "Casey", "Ronnie", "Floyd", "Reuben",
	"Clyde", "Sherman", "Andre", "Salvador", "Carmen", "Steve", "Ramon", "Jaime", "Vance", "Quinn",
	"Mitchell", "Russel", "Drew", "Karl", "Felix", "Vernon", "Cory", "Bryan", "Toby", "Heath",
	"Damon", "Geoffrey", "Sergio", "Pedro", "Kurt", "Edgar", "Ross", "Darryl", "Clarence", "Howard",
	"Norman", "Phil", "Joey", "Roland", "Hector", "Roberto", "Andy", "Ben", "Carlos", "Enrique",
	"Bobby", "Ernesto", "Felipe", "Guillermo", "Ismael", "Javier", "Julio", "Marco", "Miguel", "Oscar",
	"Rafael", "Ricardo", "Rodrigo", "Santiago", "Sergio", "Tomas", "Victor", "Adriano", "Alejandro", "Andres",
}

// englishFemaleFirstNames is a curated pool of common female first names in the
// United States drawn from the Social Security Administration baby name
// historical tables.
var englishFemaleFirstNames = []string{
	"Mary", "Patricia", "Jennifer", "Linda", "Elizabeth", "Barbara", "Susan", "Jessica", "Sarah", "Karen",
	"Lisa", "Nancy", "Betty", "Sandra", "Margaret", "Ashley", "Kimberly", "Emily", "Donna", "Michelle",
	"Carol", "Amanda", "Melissa", "Deborah", "Stephanie", "Dorothy", "Rebecca", "Sharon", "Laura", "Cynthia",
	"Amy", "Kathleen", "Angela", "Shirley", "Brenda", "Emma", "Anna", "Pamela", "Nicole", "Samantha",
	"Katherine", "Christine", "Helen", "Debra", "Rachel", "Carolyn", "Janet", "Maria", "Catherine", "Heather",
	"Diane", "Olivia", "Julie", "Joyce", "Victoria", "Ruth", "Virginia", "Lauren", "Kelly", "Christina",
	"Joan", "Evelyn", "Judith", "Andrea", "Hannah", "Megan", "Cheryl", "Jacqueline", "Martha", "Madison",
	"Teresa", "Gloria", "Sara", "Janice", "Ann", "Kathryn", "Abigail", "Sophia", "Frances", "Jean",
	"Alice", "Judy", "Isabella", "Julia", "Grace", "Amber", "Denise", "Danielle", "Marilyn", "Beverly",
	"Charlotte", "Natalie", "Theresa", "Diana", "Brittany", "Doris", "Kayla", "Alexis", "Lori", "Marie",
	"Ava", "Mia", "Amelia", "Harper", "Evelyn", "Ella", "Avery", "Sofia", "Camila", "Aria",
	"Scarlett", "Mila", "Aubrey", "Layla", "Lily", "Penelope", "Riley", "Zoey", "Nora", "Lillian",
	"Eleanor", "Hannah", "Lillian", "Addison", "Aubree", "Ellie", "Stella", "Natalie", "Zoe", "Leah",
	"Hazel", "Violet", "Aurora", "Savannah", "Audrey", "Brooklyn", "Bella", "Claire", "Skylar", "Lucy",
	"Paisley", "Everly", "Anna", "Caroline", "Nova", "Genesis", "Emilia", "Kennedy", "Samantha", "Maya",
	"Willow", "Kinsley", "Naomi", "Aaliyah", "Elena", "Sarah", "Ariana", "Allison", "Gabriella", "Alice",
	"Madelyn", "Cora", "Ruby", "Eva", "Serenity", "Autumn", "Adeline", "Hailey", "Gianna", "Valentina",
	"Isla", "Eliana", "Quinn", "Nevaeh", "Ivy", "Sadie", "Piper", "Lydia", "Alyssa", "Alexa",
	"Josephine", "Emery", "Julia", "Delilah", "Arianna", "Vivian", "Kaylee", "Sophie", "Brielle", "Madeline",
	"Peyton", "Rylee", "Clara", "Hadley", "Melanie", "Mackenzie", "Reagan", "Adalynn", "Liliana", "Aubrie",
	"Khloe", "Lila", "Paige", "Rylie", "Adalyn", "Athena", "Melody", "Kira", "Kelsey", "Mariah",
	"Crystal", "Erin", "Tiffany", "Lindsey", "Veronica", "Rose", "Tracy", "Holly", "Mildred", "Carmen",
	"Jamie", "Anita", "Dolores", "Lori", "Renee", "Edith", "Patty", "Sherry", "Lola", "Sylvia",
	"Lucia", "Hope", "Sherri", "Yolanda", "Connie", "Megan", "Roberta", "Beatrice", "Becky", "Erika",
	"Geraldine", "Wendy", "Stacey", "Maxine", "Joanna", "Eleanor", "Tammy", "Toni", "Bonnie", "Norma",
	"Yvonne", "Stacy", "Loretta", "Lillie", "Jenna", "Kimberley", "Faith", "Naomi", "Yvette", "Iris",
	"Rita", "Glenda", "Misty", "Charlene", "Maggie", "Cassandra", "Casey", "Erica", "Esther", "Adrienne",
	"Kristen", "Krista", "Tara", "Vicky", "Bernice", "Bobbie", "Whitney", "Latoya", "Cecilia", "Ethel",
	"Lucille", "Susie", "Daisy", "Pearl", "Velma", "Phyllis", "Wanda", "Irene", "Rosa", "Florence",
	"Maureen", "Marian", "Pauline", "Geneva", "Lorraine", "Bertha", "Eunice", "Lucinda", "Estelle", "Inez",
}

// englishCities is a curated pool of major U.S. cities with province (state)
// and approximate geo-coordinates sourced from publicly available geographic
// data.
var englishCities = []CityEntry{
	{Name: "New York", Province: "New York", Lat: 40.7128, Lng: -74.0060},
	{Name: "Los Angeles", Province: "California", Lat: 34.0522, Lng: -118.2437},
	{Name: "Chicago", Province: "Illinois", Lat: 41.8781, Lng: -87.6298},
	{Name: "Houston", Province: "Texas", Lat: 29.7604, Lng: -95.3698},
	{Name: "Phoenix", Province: "Arizona", Lat: 33.4484, Lng: -112.0740},
	{Name: "Philadelphia", Province: "Pennsylvania", Lat: 39.9526, Lng: -75.1652},
	{Name: "San Antonio", Province: "Texas", Lat: 29.4241, Lng: -98.4936},
	{Name: "San Diego", Province: "California", Lat: 32.7157, Lng: -117.1611},
	{Name: "Dallas", Province: "Texas", Lat: 32.7767, Lng: -96.7970},
	{Name: "San Jose", Province: "California", Lat: 37.3382, Lng: -121.8863},
	{Name: "Austin", Province: "Texas", Lat: 30.2672, Lng: -97.7431},
	{Name: "Jacksonville", Province: "Florida", Lat: 30.3322, Lng: -81.6557},
	{Name: "Fort Worth", Province: "Texas", Lat: 32.7555, Lng: -97.3308},
	{Name: "Columbus", Province: "Ohio", Lat: 39.9612, Lng: -82.9988},
	{Name: "Charlotte", Province: "North Carolina", Lat: 35.2271, Lng: -80.8431},
	{Name: "Indianapolis", Province: "Indiana", Lat: 39.7684, Lng: -86.1581},
	{Name: "San Francisco", Province: "California", Lat: 37.7749, Lng: -122.4194},
	{Name: "Seattle", Province: "Washington", Lat: 47.6062, Lng: -122.3321},
	{Name: "Denver", Province: "Colorado", Lat: 39.7392, Lng: -104.9903},
	{Name: "Washington", Province: "District of Columbia", Lat: 38.9072, Lng: -77.0369},
	{Name: "Boston", Province: "Massachusetts", Lat: 42.3601, Lng: -71.0589},
	{Name: "El Paso", Province: "Texas", Lat: 31.7619, Lng: -106.4850},
	{Name: "Nashville", Province: "Tennessee", Lat: 36.1627, Lng: -86.7816},
	{Name: "Detroit", Province: "Michigan", Lat: 42.3314, Lng: -83.0458},
	{Name: "Oklahoma City", Province: "Oklahoma", Lat: 35.4676, Lng: -97.5164},
	{Name: "Portland", Province: "Oregon", Lat: 45.5152, Lng: -122.6784},
	{Name: "Las Vegas", Province: "Nevada", Lat: 36.1699, Lng: -115.1398},
	{Name: "Memphis", Province: "Tennessee", Lat: 35.1495, Lng: -90.0490},
	{Name: "Louisville", Province: "Kentucky", Lat: 38.2527, Lng: -85.7585},
	{Name: "Baltimore", Province: "Maryland", Lat: 39.2904, Lng: -76.6122},
	{Name: "Milwaukee", Province: "Wisconsin", Lat: 43.0389, Lng: -87.9065},
	{Name: "Albuquerque", Province: "New Mexico", Lat: 35.0844, Lng: -106.6504},
	{Name: "Tucson", Province: "Arizona", Lat: 32.2226, Lng: -110.9747},
	{Name: "Fresno", Province: "California", Lat: 36.7378, Lng: -119.7871},
	{Name: "Mesa", Province: "Arizona", Lat: 33.4152, Lng: -111.8315},
	{Name: "Sacramento", Province: "California", Lat: 38.5816, Lng: -121.4944},
	{Name: "Atlanta", Province: "Georgia", Lat: 33.7490, Lng: -84.3880},
	{Name: "Kansas City", Province: "Missouri", Lat: 39.0997, Lng: -94.5786},
	{Name: "Colorado Springs", Province: "Colorado", Lat: 38.8339, Lng: -104.8214},
	{Name: "Miami", Province: "Florida", Lat: 25.7617, Lng: -80.1918},
	{Name: "Raleigh", Province: "North Carolina", Lat: 35.7796, Lng: -78.6382},
	{Name: "Omaha", Province: "Nebraska", Lat: 41.2565, Lng: -95.9345},
	{Name: "Long Beach", Province: "California", Lat: 33.7701, Lng: -118.1937},
	{Name: "Virginia Beach", Province: "Virginia", Lat: 36.8529, Lng: -75.9780},
	{Name: "Oakland", Province: "California", Lat: 37.8044, Lng: -122.2712},
	{Name: "Minneapolis", Province: "Minnesota", Lat: 44.9778, Lng: -93.2650},
	{Name: "Tulsa", Province: "Oklahoma", Lat: 36.1540, Lng: -95.9928},
	{Name: "Arlington", Province: "Texas", Lat: 32.7357, Lng: -97.1081},
	{Name: "New Orleans", Province: "Louisiana", Lat: 29.9511, Lng: -90.0715},
	{Name: "Wichita", Province: "Kansas", Lat: 37.6872, Lng: -97.3301},
	{Name: "Cleveland", Province: "Ohio", Lat: 41.4993, Lng: -81.6944},
	{Name: "Tampa", Province: "Florida", Lat: 27.9506, Lng: -82.4572},
	{Name: "Bakersfield", Province: "California", Lat: 35.3733, Lng: -119.0187},
	{Name: "Aurora", Province: "Colorado", Lat: 39.7294, Lng: -104.8319},
	{Name: "Honolulu", Province: "Hawaii", Lat: 21.3069, Lng: -157.8583},
	{Name: "Anchorage", Province: "Alaska", Lat: 61.2181, Lng: -149.9003},
	{Name: "Santa Fe", Province: "New Mexico", Lat: 35.6870, Lng: -105.9378},
	{Name: "Salt Lake City", Province: "Utah", Lat: 40.7608, Lng: -111.8910},
	{Name: "Boise", Province: "Idaho", Lat: 43.6150, Lng: -116.2023},
	{Name: "Helena", Province: "Montana", Lat: 46.5891, Lng: -112.0391},
	{Name: "Cheyenne", Province: "Wyoming", Lat: 41.1400, Lng: -104.8202},
	{Name: "Bismarck", Province: "North Dakota", Lat: 46.8083, Lng: -100.7837},
	{Name: "Pierre", Province: "South Dakota", Lat: 44.3683, Lng: -100.3510},
	{Name: "Lincoln", Province: "Nebraska", Lat: 40.8136, Lng: -96.7026},
	{Name: "Topeka", Province: "Kansas", Lat: 39.0473, Lng: -95.6752},
	{Name: "Des Moines", Province: "Iowa", Lat: 41.5868, Lng: -93.6250},
	{Name: "Madison", Province: "Wisconsin", Lat: 43.0731, Lng: -89.4012},
	{Name: "Saint Paul", Province: "Minnesota", Lat: 44.9537, Lng: -93.0900},
	{Name: "Jefferson City", Province: "Missouri", Lat: 38.5767, Lng: -92.1735},
	{Name: "Little Rock", Province: "Arkansas", Lat: 34.7465, Lng: -92.2896},
	{Name: "Baton Rouge", Province: "Louisiana", Lat: 30.4515, Lng: -91.1871},
	{Name: "Jackson", Province: "Mississippi", Lat: 32.2988, Lng: -90.1848},
	{Name: "Montgomery", Province: "Alabama", Lat: 32.3792, Lng: -86.3077},
	{Name: "Tallahassee", Province: "Florida", Lat: 30.4383, Lng: -84.2807},
	{Name: "Columbia", Province: "South Carolina", Lat: 34.0007, Lng: -81.0348},
	{Name: "Frankfort", Province: "Kentucky", Lat: 38.2009, Lng: -84.8733},
	{Name: "Springfield", Province: "Illinois", Lat: 39.7817, Lng: -89.6501},
	{Name: "Lansing", Province: "Michigan", Lat: 42.7325, Lng: -84.5555},
	{Name: "Charleston", Province: "West Virginia", Lat: 38.3498, Lng: -81.6326},
	{Name: "Richmond", Province: "Virginia", Lat: 37.5407, Lng: -77.4360},
	{Name: "Annapolis", Province: "Maryland", Lat: 38.9784, Lng: -76.4922},
	{Name: "Harrisburg", Province: "Pennsylvania", Lat: 40.2732, Lng: -76.8867},
	{Name: "Trenton", Province: "New Jersey", Lat: 40.2206, Lng: -74.7597},
	{Name: "Albany", Province: "New York", Lat: 42.6526, Lng: -73.7562},
	{Name: "Hartford", Province: "Connecticut", Lat: 41.7658, Lng: -72.6734},
	{Name: "Providence", Province: "Rhode Island", Lat: 41.8240, Lng: -71.4128},
	{Name: "Concord", Province: "New Hampshire", Lat: 43.2081, Lng: -71.5376},
	{Name: "Montpelier", Province: "Vermont", Lat: 44.2601, Lng: -72.5754},
	{Name: "Augusta", Province: "Maine", Lat: 44.3106, Lng: -69.7795},
	{Name: "Dover", Province: "Delaware", Lat: 39.1582, Lng: -75.5244},
	{Name: "Olympia", Province: "Washington", Lat: 47.0379, Lng: -122.9007},
	{Name: "Salem", Province: "Oregon", Lat: 44.9429, Lng: -123.0351},
	{Name: "Carson City", Province: "Nevada", Lat: 39.1638, Lng: -119.7674},
}

// englishStreets is a curated pool of common U.S. street-name templates used
// to compose synthetic addresses.
var englishStreets = []string{
	"Main St", "Oak Ave", "Maple Dr", "Cedar Ln", "Elm St", "Park Ave", "Washington St", "Lincoln Ave", "Jefferson St", "Madison Ave",
	"Lake Dr", "Hill Rd", "River St", "Pine St", "Spruce Ln", "Cherry Blvd", "Forest Ave", "Sunset Blvd", "Highland Ave", "Mountain View Rd",
	"Broadway", "Market St", "Church St", "Mill Rd", "Walnut St", "Chestnut St", "Pearl St", "Water St", "Center St", "School St",
	"High St", "Union St", "Adams St", "Franklin St", "Hamilton St", "Jackson St", "Monroe St", "Roosevelt Ave", "Kennedy Blvd", "Grant St",
	"Bridge St", "Front St", "Spring St", "Summer St", "Winter St", "Autumn Ln", "North Ave", "South Ave", "East St", "West St",
	"Meadow Ln", "Brook St", "Glen Rd", "Valley Dr", "Ridge Rd", "Hilltop Dr", "Lakeview Dr", "Riverside Dr", "Bayview Ave", "Ocean Blvd",
	"Beach Rd", "Harbor Dr", "Pier Ave", "Bay St", "Coast Hwy", "Canyon Rd", "Mesa Dr", "Desert Ln", "Prairie Ave", "Plains Rd",
	"Fairview Ave", "Oakwood Dr", "Birch Ln", "Aspen Way", "Sycamore St", "Willow Ln", "Magnolia Ave", "Dogwood Dr", "Hickory Ln", "Poplar St",
	"College Ave", "University Dr", "Campus Way", "Library Ln", "Court St", "Capitol Ave", "State St", "Commerce St", "Industrial Pkwy", "Technology Dr",
	"Liberty St", "Freedom Way", "Independence Ave", "Constitution Ave", "Heritage Dr", "Pioneer Rd", "Founders Way", "Patriot Ln", "Veterans Blvd", "Memorial Dr",
}
